/* ThrillDex — adventures survived. stat = the number that matters. */
registerCatalog("thrills", [
// THE EDGE (legendaries)
{id:"th001",name:"Cage Dive with Great Whites",cat:"Water",style:"Apex Encounter",country:"Gansbaai, South Africa",stat:"4m shark",tags:["cage","cold water","primal"],fact:"The cage is aluminum. Your calm is not.",serve:"Winter season, morning boat, no caffeine.",leg:true},
{id:"th002",name:"Heli-Ski Drop",cat:"Snow & Ice",style:"Untracked Descent",country:"British Columbia, Canada",stat:"3,000m",tags:["powder","helicopter","earned silence"],fact:"The heli leaves. The silence that follows is the whole point.",serve:"Ride with a guide, respect the avalanche brief.",leg:true},
{id:"th003",name:"Summit a 6,000m Peak",cat:"Land",style:"High Altitude",country:"Himalaya / Andes",stat:"6,000m+",tags:["thin air","alpine start","suffering"],fact:"Above 6,000m your body is slowly dying. You go anyway.",serve:"Acclimatize properly — the mountain waits.",leg:true},
{id:"th004",name:"Bloukrans Bungee",cat:"Air",style:"World's Highest Bridge Jump",country:"South Africa",stat:"216m",tags:["7 seconds","bridge","commitment"],fact:"The world's highest commercial bridge bungee — seven seconds of pure fall.",serve:"Don't look down. Look out.",leg:true},
{id:"th005",name:"Solo Skydive (AFF)",cat:"Air",style:"Licensed Freefall",country:"Anywhere with sky",stat:"4,000m",tags:["own parachute","training","graduation"],fact:"Tandem is a ride. Solo is a decision you make alone at altitude.",serve:"Complete AFF; your first solo pull is yours forever.",leg:true},
// AIR
{id:"th006",name:"Tandem Skydive",cat:"Air",style:"First Freefall",country:"Anywhere with sky",stat:"60s freefall",tags:["door moment","scream","convert"],fact:"Nobody remembers the plane ride up. Everybody remembers the door.",serve:"Morning slot for calm air; over water or desert."},
{id:"th007",name:"Paragliding in Bir",cat:"Air",style:"Himalayan Soaring",country:"Bir Billing, India",stat:"2,400m launch",tags:["thermals","himalaya","world site"],fact:"One of the world's best paragliding sites is a Tibetan colony in Himachal.",serve:"October window, fly the long ridge."},
{id:"th008",name:"Hot Air Balloon Flight",cat:"Air",style:"Dawn Drift",country:"Cappadocia or beyond",stat:"5:00 AM",tags:["silent","burner roar","champagne landing"],fact:"Ballooning tradition ends every flight with champagne — since the Montgolfiers.",serve:"Dawn only. Bring layers, not fear."},
{id:"th009",name:"Zipline Over a Canyon",cat:"Air",style:"Cable Run",country:"Ras Al Khaimah, UAE",stat:"150 km/h",tags:["jebel jais","superman","longest"],fact:"The world's longest zipline hangs off a UAE mountain.",serve:"Superman position, eyes open."},
{id:"th010",name:"Indoor Skydiving",cat:"Air",style:"Wind Tunnel",country:"Anywhere",stat:"200 km/h wind",tags:["bodyflight","training","gateway"],fact:"Tunnel time is how world-champion skydivers actually train.",serve:"Two flights minimum — the second one clicks."},
{id:"th011",name:"Microlight Flight",cat:"Air",style:"Open Cockpit",country:"Victoria Falls, Zambia",stat:"500m over falls",tags:["no doors","spray","angel view"],fact:"An open seat over the smoke that thunders.",serve:"Morning light, camera mounted, hands free."},
{id:"th012",name:"Gorge Swing",cat:"Air",style:"Free Swing",country:"Graskop / Queenstown",stat:"70m drop",tags:["pendulum","free fall","screaming arc"],fact:"Falls like a bungee, swings like a wrecking ball.",serve:"Go backwards if you dare."},
// WATER
{id:"th013",name:"Open Water Scuba Cert",cat:"Water",style:"First License",country:"Anywhere with reef",stat:"18m",tags:["breathe underwater","license","new world"],fact:"The certification card is a passport to 71% of the planet.",serve:"Do it somewhere warm; log every dive."},
{id:"th014",name:"Night Dive",cat:"Water",style:"Torchlit Descent",country:"Any dark sea",stat:"1 torch",tags:["bioluminescence","nerves","hunting hour"],fact:"Cover your torch, wave your hand — the sea lights up around you.",serve:"With a guide, after 20+ logged dives."},
{id:"th015",name:"White Water Rafting, Rishikesh",cat:"Water",style:"Ganga Rapids",country:"Rishikesh, India",stat:"Grade IV",tags:["golf course rapid","cold ganga","team"],fact:"The rapid named 'Golf Course' has ended many dry runs.",serve:"Sept–Nov water; jump in at the calm stretch."},
{id:"th016",name:"Surf Your First Green Wave",cat:"Water",style:"The Real Thing",country:"Anywhere with swell",stat:"1 wave",tags:["pop up","unbroken face","addiction begins"],fact:"Whitewash is practice. Your first green wall is the drug.",serve:"Small day, point break, count it loud."},
{id:"th017",name:"Kitesurf a Full Run",cat:"Water",style:"Wind Powered",country:"Kite Beach or beyond",stat:"20 knots",tags:["body drag","upwind","flight"],fact:"You'll drink a lot of sea before you fly over it.",serve:"Lessons first — kites don't forgive."},
{id:"th018",name:"Canyoning Descent",cat:"Water",style:"Gorge Route",country:"Interlaken / Himachal",stat:"6 rappels",tags:["waterfall rappel","jumps","wetsuit"],fact:"Part climbing, part swimming, part controlled falling.",serve:"Guided route; commit to the first jump fast."},
{id:"th019",name:"Freedive to 10m",cat:"Water",style:"One Breath",country:"Any blue hole",stat:"1 breath",tags:["equalize","calm","mammalian reflex"],fact:"Your body carries a dive reflex older than land.",serve:"Never alone. Course first, ego last."},
{id:"th020",name:"Swim a Shipwreck",cat:"Water",style:"Wreck Dive",country:"Red Sea / Coron",stat:"WWII era",tags:["history","swim-through","ghost ship"],fact:"The sea keeps its museums exactly where they sank.",serve:"Wreck-certified guide; touch nothing."},
{id:"th021",name:"Jet Ski Open Water",cat:"Water",style:"Throttle Therapy",country:"Dubai Marina & beyond",stat:"100 km/h",tags:["chop","spray","skyline"],fact:"The Dubai skyline was designed to be seen at throttle.",serve:"Morning glass-water slot."},
// LAND
{id:"th022",name:"Trek to Everest Base Camp",cat:"Land",style:"Pilgrimage Trek",country:"Nepal",stat:"5,364m",tags:["12 days","khumbu","teahouses"],fact:"The trail is a two-week queue of people meeting themselves.",serve:"Go slow, drink garlic soup, tip your porter."},
{id:"th023",name:"Via Ferrata Route",cat:"Land",style:"Iron Path",country:"Dolomites, Italy",stat:"300m exposure",tags:["cables","ww1 routes","exposure"],fact:"The iron paths were built by soldiers in WWI.",serve:"Clip discipline: one carabiner always on."},
{id:"th024",name:"Rock Climb Outdoors (5a+)",cat:"Land",style:"Real Rock",country:"Hampi / Badami / beyond",stat:"20m pitch",tags:["granite","trust the rope","send"],fact:"Hampi's boulders made India a world bouldering pilgrimage.",serve:"With a certified lead; scream 'take' proudly."},
{id:"th025",name:"Motorbike the Leh Highway",cat:"Land",style:"High Passes Ride",country:"Manali–Leh, India",stat:"5,359m pass",tags:["royal enfield","khardung la","breakdowns"],fact:"The bike will break. That's part of the itinerary.",serve:"June–Sept; carry spare clutch cable and patience."},
{id:"th026",name:"Dawn at the Camel Races",cat:"Land",style:"Desert Derby",country:"Al Marmoom, UAE",stat:"40 km/h camels",tags:["robot jockeys","dawn","surreal"],fact:"The jockeys are robots; the owners drive alongside yelling into radios.",serve:"Winter Fridays, sunrise, free entry."},
{id:"th027",name:"Sandboarding Big Dunes",cat:"Land",style:"Desert Descent",country:"Namibia / UAE / Peru",stat:"100m dune",tags:["face full of sand","wax","climb again"],fact:"The ride is 20 seconds. The climb back is the sport.",serve:"Wax the base, lean back, commit."},
{id:"th028",name:"Caving Expedition",cat:"Land",style:"Underworld",country:"Meghalaya, India",stat:"-120m",tags:["headlamp","squeeze","krem"],fact:"Meghalaya hides some of Asia's longest cave systems under its hills.",serve:"Dry season only, guided, triple light sources."},
{id:"th029",name:"Horseback Safari",cat:"Land",style:"Ride Among Game",country:"Masai Mara / Botswana",stat:"Eye level",tags:["no engine","zebra herds","ancient"],fact:"On a horse, wildlife reads you as animal, not vehicle.",serve:"Riders only — this is not a pony ride."},
{id:"th030",name:"Canyon Swing / Cliff Jump (guided)",cat:"Land",style:"Commitment Step",country:"Queenstown, NZ",stat:"109m",tags:["step off","gut drop","laughter after"],fact:"Queenstown made stepping off cliffs a customer experience.",serve:"Choose the 'backwards in a chair' exit."},
// SNOW & ICE
{id:"th031",name:"First Black Run",cat:"Snow & Ice",style:"Ski Milestone",country:"Alps / Gulmarg",stat:"Black grade",tags:["knees","commitment","fall line"],fact:"The mountain doesn't grade on effort.",serve:"Ski it early, legs fresh, ego stowed."},
{id:"th032",name:"Ski Gulmarg Bowl",cat:"Snow & Ice",style:"Himalayan Off-Piste",country:"Kashmir, India",stat:"3,980m gondola",tags:["powder","apharwat","himalaya"],fact:"One of the highest gondolas on Earth opens Himalayan powder.",serve:"Hire a local guide; Jan–Feb snow."},
{id:"th033",name:"Ice Climbing",cat:"Snow & Ice",style:"Frozen Vertical",country:"Ouray / Spiti",stat:"WI3",tags:["ice axes","crampons","screaming barfies"],fact:"'Screaming barfies' is the technical term for the hand-rewarming pain.",serve:"Guided top-rope first; swing from the wrist."},
{id:"th034",name:"Glacier Hike",cat:"Snow & Ice",style:"Crampon Walk",country:"Iceland / NZ",stat:"1,000yr ice",tags:["crevasse","blue ice","rope team"],fact:"You are walking on compressed snowfall from before your grandparents.",serve:"Roped, guided, helmeted — always."},
{id:"th035",name:"Dog Sledding",cat:"Snow & Ice",style:"Mush Your Team",country:"Lapland / Svalbard",stat:"6-dog team",tags:["silence","huskies","brake pedal"],fact:"The dogs scream to run and fall silent the instant they do.",serve:"Drive your own sled, not the tourist seat."},
{id:"th036",name:"Polar Plunge",cat:"Snow & Ice",style:"Cold Shock",country:"Any frozen water",stat:"2°C",tags:["gasp","afterglow","bragging rights"],fact:"The afterglow is chemical and it is glorious.",serve:"Supervised, quick exit plan, warm layers ready."},
{id:"th037",name:"Snowmobile Wilderness Run",cat:"Snow & Ice",style:"Throttle North",country:"Lapland, Finland",stat:"-20°C",tags:["frozen lake","headlights","aurora chance"],fact:"Crossing a frozen lake at night feels like driving on the moon.",serve:"Night safari, thermal suit provided."},
// SPEED
{id:"th038",name:"F1 Circuit Track Day",cat:"Speed",style:"Real Tarmac",country:"Yas Marina, UAE",stat:"5.28 km lap",tags:["apex","g-force","radio"],fact:"Yas Marina lets civilians lap a real F1 calendar circuit.",serve:"Instructor lap first, then chase your delta."},
{id:"th039",name:"Supercar Lap",cat:"Speed",style:"Dream Garage",country:"Dubai Autodrome & beyond",stat:"300 km/h car",tags:["launch control","valley of speed","grin"],fact:"Launch control is legal violence.",serve:"Pick the car you had on your wall."},
{id:"th040",name:"Karting Race (proper)",cat:"Speed",style:"Wheel-to-Wheel",country:"Anywhere",stat:"70 km/h feels like 200",tags:["racecraft","elbows","podium"],fact:"Every F1 champion started exactly here.",serve:"Race night league, not arcade sessions."},
{id:"th041",name:"Off-Road Dune Driving (own wheel)",cat:"Speed",style:"Self-Drive Desert",country:"Al Qudra, UAE",stat:"33° dune face",tags:["deflate tyres","crest slow","recovery"],fact:"Rule one: never crest a dune at speed — the other side votes.",serve:"Convoy with spotters, tyres at 15 psi."},
{id:"th042",name:"Rally Co-Driver Ride",cat:"Speed",style:"Pace Notes",country:"Anywhere gravel",stat:"6 left over crest",tags:["sideways","trust","gravel"],fact:"The driver never sees the corner — they hear it from you.",serve:"Eat light. Seriously."},
{id:"th043",name:"Fighter Jet Aerobatic Ride",cat:"Speed",style:"Aerobatic Flight",country:"L-39 programs worldwide",stat:"+6G",tags:["barrel roll","g-suit","legend status"],fact:"At +6G your blood weighs six times more than your heart expects.",serve:"Tense your legs, breathe in bursts."},
{id:"th044",name:"Downhill MTB Park Run",cat:"Speed",style:"Gravity Line",country:"Whistler / Bir",stat:"1,000m descent",tags:["berms","drops","armor"],fact:"The lift takes your bike up; gravity handles negotiations.",serve:"Full armor, follow a local's line."},
{id:"th045",name:"Skeleton / Luge Taster",cat:"Speed",style:"Ice Track",country:"Innsbruck / Lillehammer",stat:"90 km/h",tags:["face first","olympic track","5 seconds regret"],fact:"Face-first, chin an inch off Olympic ice.",serve:"Public taster runs exist. Book one."}
]);
