/* BarDex — extremely curated: rooms to drink a Bourdain-shaped life in.
   The Bourdain Trail = his verified on-screen stops. Everything else
   earns its place by his rules: ghosts, regulars, ritual, zero pretense. */
registerCatalog("bars", [
// THE SEVEN DOORS (legendaries)
{id:"br001",tier:"l",name:"Old Colony Tap",cat:"The Bourdain Trail",style:"Where It All Began",country:"Provincetown, USA",stat:"Since 1937",tags:["bourdain drank here","where fishermen eat","driftwood walls"],fact:"Bourdain washed dishes down the street in the 70s and came back on Parts Unknown for Wellfleet oysters — he called this 'where fishermen eat.' The last dive of old P-town.",serve:"Cheap beer, a shot, the jukebox. Cash only.",leg:true},
{id:"br002",tier:"l",name:"El Floridita",cat:"Institutions",style:"Daiquiri Cathedral",country:"Havana, Cuba",stat:"Since 1817",tags:["hemingway","frozen daiquiri","pink jackets"],fact:"Hemingway's corner stool is roped off, a bronze of him still drinking on it.",serve:"Daiquiri No.4, double, no sugar.",leg:true},
{id:"br003",tier:"l",name:"La Venencia",cat:"At the Source",style:"Sherry Time Capsule",country:"Madrid, Spain",stat:"Since 1928",tags:["no photos","cash only","civil war rules"],fact:"Republican rules from the Civil War still hold: no photos, no tips, tabs in chalk on the bar.",serve:"Manzanilla poured from height. Say nothing of politics.",leg:true},
{id:"br004",tier:"l",name:"Sean's Bar",cat:"Institutions",style:"Oldest on Earth",country:"Athlone, Ireland",stat:"Since 900 AD",tags:["1100 years","peat fire","sawdust floor"],fact:"Certified the oldest pub in the world — pouring since 900 AD, wattle walls to prove it.",serve:"A Guinness by the fire, slowly.",leg:true},
{id:"br005",tier:"l",name:"Bar Albatross",cat:"The Bourdain Trail",style:"Golden Gai Matchbox",country:"Shinjuku, Tokyo",stat:"~9 seats",tags:["bourdain drank here","golden gai","chandelier squeeze"],fact:"Bourdain's Golden Gai stop on Parts Unknown — where he learned the code of the two-hundred tiny bars: you confide in the bartender.",serve:"Duck in, pay the cover, tell the truth.",leg:true},
{id:"br006",tier:"l",name:"The Gravediggers",cat:"Institutions",style:"No Music, No TV",country:"Dublin, Ireland",stat:"Since 1833",tags:["kavanagh family","glasnevin cemetery","perfect pint"],fact:"Named for cemetery workers who knocked on the wall for pints. Eight generations, one family, zero televisions.",serve:"A pint and silence. That's the entire menu.",leg:true},
{id:"br007",tier:"l",name:"Mullapanthal Toddy Shop",cat:"At the Source",style:"Palm to Glass",country:"Kerala, India",stat:"Tapped at dawn",tags:["toddy","kappa & karimeen","backwater"],fact:"The toddy is tapped from the palm the same morning you drink it — it keeps fermenting in your glass while you eat.",serve:"Fresh toddy before noon, fiery kappa-meen curry alongside.",leg:true},
// THE BOURDAIN TRAIL — his verified stops
{id:"br008",tier:"r",name:"Bia Hơi Hải Xồm",cat:"The Bourdain Trail",style:"Fresh Beer, Low Stools",country:"Hanoi, Vietnam",stat:"~₫10,000",tags:["bourdain drank here","with linh","brewed daily"],fact:"Where Tony and his friend Linh clinked fresh-brewed bia hơi on Parts Unknown — beer made at dawn, gone by night.",serve:"Point at the keg, kid-sized stool, peanuts, repeat."},
{id:"br009",tier:"u",name:"Sophie's",cat:"The Bourdain Trail",style:"East Village Leveler",country:"New York, USA",stat:"Cheap & dark",tags:["bourdain drank here","pool table","no concept"],fact:"The conceptless East Village dive Bourdain loved because nobody cares what you do for a living.",serve:"Whatever's cheap, rack the pool balls."},
{id:"br010",tier:"r",name:"Sunny's Bar",cat:"The Bourdain Trail",style:"Red Hook Living Room",country:"Brooklyn, USA",stat:"Since 1890s",tags:["bourdain drank here","waterfront","banjo nights"],fact:"A longshoreman's bar at the end of Red Hook that Bourdain treasured — musicians, sailors, and the feeling of being discovered, not consumed.",serve:"Whiskey during the bluegrass jam."},
{id:"br011",tier:"r",name:"Neir's Tavern",cat:"The Bourdain Trail",style:"1829 Survivor",country:"Queens, USA",stat:"Since 1829",tags:["bourdain drank here","goodfellas","oldest in NY"],fact:"One of America's oldest bars, hiding in Woodhaven — Goodfellas filmed here; Bourdain used it to prove New York gets better outside Manhattan.",serve:"A beer at the original mahogany."},
{id:"br012",tier:"r",name:"Ms. Mae's",cat:"The Bourdain Trail",style:"24-Hour Institution",country:"New Orleans, USA",stat:"Open 24/7",tags:["bourdain trail","the club","never closes"],fact:"The Uptown dive that never closes — on Bourdain's New Orleans map since A Cook's Tour.",serve:"A cheap double at an hour you won't admit to."},
{id:"br013",tier:"c",name:"Tonga Room",cat:"The Bourdain Trail",style:"Tiki Hurricane",country:"San Francisco, USA",stat:"Since 1945",tags:["bourdain drank here","indoor rainstorm","band on a boat"],fact:"A tiki temple where it rains indoors and the band plays from a boat in the pool — Bourdain got gleefully hammered here on No Reservations.",serve:"A Zombie when the thunder starts."},
{id:"br014",tier:"r",name:"Floyd's Pelican Bar",cat:"The Bourdain Trail",style:"Bar in the Sea",country:"Parottee, Jamaica",stat:"1km offshore",tags:["bourdain trail","sandbar shack","boat access only"],fact:"A driftwood shack on a sandbar a kilometer out to sea — you arrive by boat, leave your name on a plank, and time stops.",serve:"Red Stripe with your feet in the Caribbean."},
// INSTITUTIONS
{id:"br015",tier:"c",name:"Harry's New York Bar",cat:"Institutions",style:"Sank Roo Doe Noo",country:"Paris, France",stat:"Since 1911",tags:["bloody mary","college pennants","hemingway again"],fact:"Claims the Bloody Mary, the Sidecar, and half of cocktail history — argued about ever since.",serve:"Bloody Mary at the mahogany."},
{id:"br016",tier:"c",name:"Vesuvio Cafe",cat:"Institutions",style:"Beat Landmark",country:"San Francisco, USA",stat:"Since 1948",tags:["kerouac","city lights","north beach"],fact:"Kerouac drank here instead of meeting Henry Miller. Twice.",serve:"A beer upstairs by the stained glass."},
{id:"br017",tier:"c",name:"McSorley's Old Ale House",cat:"Institutions",style:"Light or Dark",country:"New York, USA",stat:"Since 1854",tags:["two choices","sawdust","dusty wishbones"],fact:"The menu is two words: light or dark. The dust on the wishbones above the bar predates your grandparents.",serve:"'Two lights.' They come in pairs. Don't ask."},
{id:"br018",tier:"u",name:"Green Mill",cat:"Institutions",style:"Capone's Booth",country:"Chicago, USA",stat:"Since 1907",tags:["al capone","jazz nightly","trapdoors"],fact:"Capone's booth faced both doors; the tunnels below moved his whiskey. The jazz never stopped.",serve:"Late set, back booth, whiskey neat."},
{id:"br019",tier:"u",name:"Napoleon House",cat:"Institutions",style:"Crumbling Grandeur",country:"New Orleans, USA",stat:"Since 1914",tags:["pimm's cup","peeling walls","opera on vinyl"],fact:"Built to house Napoleon in exile. He never came. The bar decided to wait anyway, beautifully decaying since.",serve:"Pimm's Cup under the peeling plaster."},
{id:"br020",tier:"u",name:"Ye Olde Cheshire Cheese",cat:"Institutions",style:"Rebuilt 1667",country:"London, England",stat:"Since 1667",tags:["dickens","1200s cellars","no daylight"],fact:"Rebuilt right after the Great Fire; Dickens drank in the gloom. The cellars are older still.",serve:"An ale in the windowless front room."},
{id:"br021",tier:"u",name:"The French House",cat:"Institutions",style:"Half Pints Only",country:"Soho, London",stat:"Since 1891",tags:["no pints","francis bacon","de gaulle"],fact:"Beer in halves only, phones frowned at — De Gaulle allegedly drafted his resistance speech upstairs.",serve:"A half of lager and a proper conversation."},
{id:"br022",tier:"u",name:"U Zlatého Tygra",cat:"Institutions",style:"Hrabal's Pub",country:"Prague, Czechia",stat:"Since 1816",tags:["pilsner","hrabal","havel brought clinton"],fact:"Bohumil Hrabal held court here nightly; Havel brought Bill Clinton for a lesson in real pubs.",serve:"Unfiltered Pilsner keeps arriving until you cover the glass."},
{id:"br023",tier:"u",name:"Brettos",cat:"Institutions",style:"Wall of Glowing Bottles",country:"Athens, Greece",stat:"Since 1909",tags:["oldest distillery","plaka","backlit shelves"],fact:"Athens' oldest distillery, its glowing bottle wall older than most countries' bar scenes.",serve:"House brandy or citron liqueur, standing."},
{id:"br024",tier:"r",name:"Salón Tenampa",cat:"Institutions",style:"Mariachi Ground Zero",country:"Mexico City, Mexico",stat:"Since 1925",tags:["plaza garibaldi","murals","serenatas"],fact:"Mariachi as we know it was headquartered here — bands still roam the tables for hire.",serve:"Tequila while a trumpet plays a meter from your ear."},
{id:"br025",tier:"u",name:"Bar La Ópera",cat:"Institutions",style:"Bullet in the Ceiling",country:"Mexico City, Mexico",stat:"Since 1876",tags:["pancho villa","gilded booths","cantina"],fact:"Pancho Villa rode in and fired into the ceiling. The bullet hole is still there. So is the bar.",serve:"Tequila and botanas under the hole itself."},
{id:"br026",tier:"u",name:"Bar El Federal",cat:"Institutions",style:"Bar Notable",country:"Buenos Aires, Argentina",stat:"Since 1864",tags:["carved oak","bares notables","siphons"],fact:"One of BA's protected 'bares notables' — the carved oak arch has watched 160 years of arguments.",serve:"Vermouth con soda from the antique siphon."},
{id:"br027",tier:"r",name:"Birdsville Hotel",cat:"Institutions",style:"Outback Oasis",country:"Birdsville, Australia",stat:"Since 1884",tags:["simpson desert edge","population 100","dust storms"],fact:"A pub at the edge of the Simpson Desert serving a town of one hundred — and every soul crossing it.",serve:"A cold one with red dust still on your boots."},
{id:"br028",tier:"u",name:"The Pot Still",cat:"Institutions",style:"Whisky Parliament",country:"Glasgow, Scotland",stat:"700+ bottles",tags:["glasgow patter","dram wall","no nonsense"],fact:"Seven hundred whiskies and bartenders who'll find your dram from a hand-waved description.",serve:"Ask for something peaty and let them choose."},
// DIVES & LOCALS
{id:"br029",tier:"u",name:"Snake and Jake's Christmas Club Lounge",cat:"Dives & Locals",style:"Eternal Christmas",country:"New Orleans, USA",stat:"Til sunrise",tags:["christmas lights","no clocks","legendary dive"],fact:"A shack of year-round Christmas lights where New Orleans goes when everywhere else closes.",serve:"High Life at 4am. If the sun catches you, you did it right."},
{id:"br030",tier:"r",name:"El Batey",cat:"Dives & Locals",style:"Old San Juan Dive",country:"San Juan, Puerto Rico",stat:"Since 1970",tags:["business cards","best jukebox","cash only"],fact:"Ceiling of business cards, best jukebox in the Caribbean, zero improvements in fifty years.",serve:"Rum, neat, cash."},
{id:"br031",tier:"c",name:"Gokul",cat:"Dives & Locals",style:"Colaba Institution",country:"Mumbai, India",stat:"Since 1980s",tags:["old monk","office crowd","no frills"],fact:"Behind the Taj's shadow, Mumbai's great equalizer: bankers, sailors, and poets over Old Monk.",serve:"Old Monk with cold water, bhurji pav on the side."},
{id:"br032",tier:"c",name:"Janata Bar",cat:"Dives & Locals",style:"Bandra's Living Room",country:"Mumbai, India",stat:"Since 1975",tags:["lunch home","quarter system","everyone's been"],fact:"Bandra's worst-lit, best-loved room — every Mumbai story routes through Janata eventually.",serve:"A quarter, a soda, and solkadhi if you know."},
{id:"br033",tier:"u",name:"Kumpelnest 3000",cat:"Dives & Locals",style:"Ex-Brothel Chaos",country:"Berlin, Germany",stat:"Since 1987",tags:["carpet walls","open forever","anything goes"],fact:"A former brothel turned carpeted fever dream that has never once closed early.",serve:"Whatever. It's Kumpelnest. Stay too long."},
{id:"br034",tier:"r",name:"Wong's Place",cat:"Dives & Locals",style:"Bangkok After Hours",country:"Bangkok, Thailand",stat:"Opens ~10pm",tags:["cassette walls","wong decides","closes at dawn"],fact:"Opens when Wong feels like it, closes when the last regular leaves. The walls are cassette tapes.",serve:"A Singha among the night shift of the whole city."},
{id:"br035",tier:"r",name:"Bip Bip",cat:"Dives & Locals",style:"Samba Front Room",country:"Rio de Janeiro, Brazil",stat:"Since 1968",tags:["roda de samba","grab your own beer","silence for the music"],fact:"Take your own beer from the fridge, note it in the book, never talk over the samba circle.",serve:"Sit outside, drink honestly, applaud quietly."},
{id:"br036",tier:"u",name:"Bar Marsella",cat:"Dives & Locals",style:"Absinthe Since 1820",country:"Barcelona, Spain",stat:"Since 1820",tags:["absinthe","dust kept on purpose","picasso hemingway"],fact:"The dust on the chandeliers is original equipment. Picasso and Hemingway drank absinthe under it.",serve:"Absenta with the sugar cube and fork ritual."},
{id:"br037",tier:"r",name:"Abou Elie",cat:"Dives & Locals",style:"Communist Bunker Bar",country:"Beirut, Lebanon",stat:"12 stools",tags:["che posters","vinyl","survived everything"],fact:"A tiny red-lit cave of revolution posters that has outlasted every war outside its door.",serve:"Almaza and a long story from whoever's next to you."},
// GHOSTS & CORRESPONDENTS
{id:"br038",tier:"r",name:"Elephant Bar, Raffles Le Royal",cat:"Ghosts & Correspondents",style:"Indochine Ghosts",country:"Phnom Penh, Cambodia",stat:"Since 1929",tags:["jackie kennedy","war correspondents","femme fatale"],fact:"Jackie Kennedy's 1967 cocktail is still on the menu; the war correspondents' ghosts kept their stools.",serve:"The Femme Fatale under the ceiling fans."},
{id:"br039",tier:"u",name:"FCC Phnom Penh",cat:"Ghosts & Correspondents",style:"Correspondents' Club",country:"Phnom Penh, Cambodia",stat:"River view",tags:["foreign press","shutters open","history filed here"],fact:"Where the war press filed their copy and their sorrows, shutters open to the Tonlé Sap.",serve:"Sunset G&T on the third-floor rail."},
{id:"br040",tier:"r",name:"Hotel Continental Terrace",cat:"Ghosts & Correspondents",style:"The Quiet American",country:"Saigon, Vietnam",stat:"Since 1880",tags:["graham greene","radio catinat","war press"],fact:"Graham Greene wrote The Quiet American around this terrace; the press corps called its rumor mill 'Radio Catinat.'",serve:"A '33' beer where Fowler sat."},
// COUNTERS & RITUALS
{id:"br041",tier:"u",name:"Bar High Five",cat:"Counters & Rituals",style:"Ginza Discipline",country:"Tokyo, Japan",stat:"Since 1997",tags:["hidetsugu ueno","hand-carved ice","no menu"],fact:"Ueno-san hand-carves ice diamonds; there is no menu, only trust and a perfect White Lady.",serve:"Say a spirit and a mood. Watch the hard shake."},
{id:"br042",tier:"c",name:"Omoide Yokocho Stand Bar",cat:"Counters & Rituals",style:"Piss Alley Smoke",country:"Shinjuku, Tokyo",stat:"8 stools",tags:["yakitori smoke","postwar alleys","highballs"],fact:"Postwar black-market alleys where seventy years of yakitori smoke seasons your highball.",serve:"Highball + whatever's on the grill, elbows in."},
{id:"br043",tier:"r",name:"A Pojangmacha Night",cat:"Counters & Rituals",style:"Tent Bar",country:"Seoul, South Korea",stat:"1 tarp",tags:["soju","orange tents","strangers become uncles"],fact:"Under an orange tarp, soju and anju dissolve the distance between strangers by the second bottle.",serve:"Soju rounds, tteokbokki, pour for your neighbor never yourself."},
{id:"br044",tier:"r",name:"A Ryumochnaya Round",cat:"Counters & Rituals",style:"Vodka Standing Room",country:"St. Petersburg, Russia",stat:"50g + a bite",tags:["standing only","herring on bread","soviet relic"],fact:"Soviet-era standing bars: fifty grams of vodka, a bite of herring bread, and the whole room's honesty.",serve:"One shot, one zakuska, one toast to something real."},
{id:"br045",tier:"c",name:"Safa Meyhanesi",cat:"Counters & Rituals",style:"Rakı Table",country:"Istanbul, Türkiye",stat:"Since 1948",tags:["rakı & meze","old waiters","hours long"],fact:"A meyhane dinner is a four-hour rakı liturgy — the waiters have conducted it for decades.",serve:"Rakı with water and ice, meze forever, no rushing."},
{id:"br046",tier:"r",name:"Fendika Azmari Bet",cat:"Counters & Rituals",style:"Azmari House",country:"Addis Ababa, Ethiopia",stat:"Nightly",tags:["improvised verse","masenqo","tej honey wine"],fact:"The azmari improvises verses about the guests — you will be sung about, kindly or not.",serve:"Tej honey wine while the masenqo player finds you."},
{id:"br047",tier:"r",name:"A Shebeen Night",cat:"Counters & Rituals",style:"Township Original",country:"Soweto, South Africa",stat:"Umqombothi",tags:["township history","communal pail","kwaito"],fact:"Shebeens were illegal resistance drinking houses; now they're the township's living rooms.",serve:"Share the umqombothi; go with someone from the street."},
{id:"br048",tier:"c",name:"A Ginjinha",cat:"Counters & Rituals",style:"Standing Shot Window",country:"Lisbon, Portugal",stat:"Since 1840",tags:["sour cherry","com ou sem","60 seconds"],fact:"A doorway, a barrel, one question since 1840: with or without the cherry?",serve:"Com elas. Drink standing in the square. Done."},
// AT THE SOURCE
{id:"br049",tier:"r",name:"La Mezcaloteca",cat:"At the Source",style:"Mezcal Library",country:"Oaxaca, Mexico",stat:"By reservation",tags:["palenque bottles","tasting ritual","no cocktails"],fact:"A library, not a bar — unlabeled palenque mezcals tasted in ritual order with the people who know.",serve:"Book ahead, taste from the veladora, ask everything."},
{id:"br050",tier:"r",name:"Vino Underground",cat:"At the Source",style:"Qvevri Cellar",country:"Tbilisi, Georgia",stat:"8,000 vintages",tags:["amber wine","buried clay","winemaker owned"],fact:"Owned by natural winemakers pouring amber wines made in buried clay — the 8,000-year-old method.",serve:"Amber wine flight, then whatever the winemaker opens."},
{id:"br051",tier:"r",name:"Tuak in an Iban Longhouse",cat:"At the Source",style:"Rice Wine Rite",country:"Sarawak, Borneo",stat:"Homemade",tags:["longhouse hospitality","rice wine","bourdain's borneo"],fact:"The rice wine flows the moment you're welcomed — refusing is not on the menu. Bourdain returned to the Iban twice; the second time he left with a tattoo.",serve:"Drink what's poured, dance when pulled up."},
{id:"br052",tier:"r",name:"La Piojera",cat:"At the Source",style:"Terremoto Ground Zero",country:"Santiago, Chile",stat:"Since 1916",tags:["terremoto","pipeño wine","gloriously rowdy"],fact:"The terremoto — pipeño wine with pineapple ice cream — was named for how the floor feels after two.",serve:"One terremoto. The second is called a réplica. Beware."},
{id:"br053",tier:"r",name:"El Bolivarcito",cat:"At the Source",style:"Pisco Sour Birthplace",country:"Lima, Peru",stat:"Since 1924",tags:["gran hotel bolívar","catedral pour","faded lobby"],fact:"The Gran Hotel Bolívar's little bar pours the 'Catedral' — the pisco sour at its birthplace scale.",serve:"Catedral del pisco sour, unhurried, in the faded lobby."}
]);
