/* BookDex — 500 books actually read. Tiers: c common, u uncommon,
   r rare, l legendary (The Summits — few start them, fewer finish).
   B(title, author, country, year, cat, tier, fact, wayIn) */
const B = (t,a,co,y,c,r,f,s) => ({ name:t, style:a, country:co, stat:String(y), cat:c, tier:r, fact:f, serve:s,
  tags:[a.split(" ").pop().toLowerCase(), r==="l"?"summit":r==="r"?"rare":"shelf"] });
const BOOKS = [
// ---- INTAKE COMMONS (bk001–bk012) ----
B("1984","George Orwell","England",1949,"Classics","c","Wrote the vocabulary every surveillance debate still uses.","One sitting steals your sleep anyway."),
B("The Great Gatsby","F. Scott Fitzgerald","USA",1925,"Classics","c","The American Dream, embalmed in champagne.","A summer weekend, preferably poolside."),
B("To Kill a Mockingbird","Harper Lee","USA",1960,"Classics","c","One novel, one Pulitzer, decades of silence after.","Let Scout narrate; don't rush her."),
B("Animal Farm","George Orwell","England",1945,"Classics","c","The revolution betrayed, in eighty pages of barnyard.","An afternoon. Then read the news."),
B("Harry Potter and the Philosopher's Stone","J.K. Rowling","England",1997,"SF & Fantasy","c","Rejected twelve times before conquering Earth.","Aloud, to someone younger."),
B("The Alchemist","Paulo Coelho","Brazil",1988,"World","c","Written in two weeks; translated into 80+ languages.","Airport bench, one flight."),
B("The Kite Runner","Khaled Hosseini","Afghanistan",2003,"World","c","Kabul before and after — and the cost of cowardice.","Keep tissues; don't read on planes."),
B("Sapiens","Yuval Noah Harari","Israel",2011,"Ideas & Science","c","Made 70,000 years of history a beach read.","Argue with it out loud."),
B("The Da Vinci Code","Dan Brown","USA",2003,"Mystery & Noir","c","Made half the planet a symbologist for one summer.","Guiltily, quickly, completely."),
B("Atomic Habits","James Clear","USA",2018,"Ideas & Science","c","The 1%-better gospel of the modern office.","With a pencil and one habit in mind."),
B("The Little Prince","Antoine de Saint-Exupéry","France",1943,"Classics","c","A children's book adults reread until it hurts.","Twice: at 12, and after 30."),
B("The God of Small Things","Arundhati Roy","India",1997,"India","c","A debut that won the Booker and rearranged English.","Slowly — the sentences are rivers."),
// ---- CLASSICS ----
B("Ulysses","James Joyce","Ireland",1922,"Classics","l","One Dublin day containing all of literature.","June 16th, with a guide, no shame.",),
B("In Search of Lost Time","Marcel Proust","France",1913,"Classics","l","Seven volumes launched by one madeleine.","A year of bedtimes. Worth it."),
B("Finnegans Wake","James Joyce","Ireland",1939,"Classics","l","Written in a language of its own invention.","Read aloud; understanding is optional."),
B("War and Peace","Leo Tolstoy","Russia",1869,"Classics","l","Napoleon invades; 559 characters respond.","A winter. Keep the name chart close."),
B("Don Quixote","Miguel de Cervantes","Spain",1605,"Classics","l","The first modern novel, still the funniest.","Tilt at it in long afternoons."),
B("Moby-Dick","Herman Melville","USA",1851,"Classics","l","A whale, an obsession, and 100 pages on rope.","Skip nothing — the rope is the point."),
B("The Brothers Karamazov","Fyodor Dostoevsky","Russia",1880,"Classics","l","God, murder, and Russia at the family table.","The Grand Inquisitor chapter twice."),
B("Middlemarch","George Eliot","England",1871,"Classics","l","The novel novelists call the greatest.","In your thirties; it lands harder."),
B("Crime and Punishment","Fyodor Dostoevsky","Russia",1866,"Classics","u","An axe, a theory, and the longest guilt in print.","In summer heat, like Raskolnikov's."),
B("Anna Karenina","Leo Tolstoy","Russia",1877,"Classics","u","Every unhappy family, and one train.","Take the Levin chapters seriously."),
B("Pride and Prejudice","Jane Austen","England",1813,"Classics","c","Two centuries of romance runs on this engine.","Aloud — the dialogue is choreography."),
B("Jane Eyre","Charlotte Brontë","England",1847,"Classics","c","The governess who demanded to be somebody.","By lamplight, storm outside."),
B("Wuthering Heights","Emily Brontë","England",1847,"Classics","u","A love story people mistake for romance.","On the moors of a bad mood."),
B("Great Expectations","Charles Dickens","England",1861,"Classics","c","Dickens' most perfect machine of a plot.","Serial-style: three chapters a night."),
B("David Copperfield","Charles Dickens","England",1850,"Classics","u","Dickens' own favorite of his children.","Long train journeys."),
B("The Odyssey","Homer","Greece",-700,"Classics","u","The template for every journey story since.","Wilson's translation, aloud."),
B("The Iliad","Homer","Greece",-750,"Classics","r","Rage, bronze, and the birth of Western literature.","With a map of Troy nearby."),
B("The Divine Comedy","Dante Alighieri","Italy",1320,"Classics","r","Hell has a floor plan because Dante drew it.","Inferno first; earn Paradiso."),
B("Hamlet","William Shakespeare","England",1603,"Verse & Stage","c","The play the English language keeps quoting by accident.","Watch one production, then read."),
B("Macbeth","William Shakespeare","England",1606,"Verse & Stage","c","Ambition's autopsy in five acts.","In one dark evening sitting."),
B("King Lear","William Shakespeare","England",1606,"Verse & Stage","u","The storm scene alone justifies theatre.","After 40, ideally with parents living."),
B("The Tempest","William Shakespeare","England",1611,"Verse & Stage","u","Shakespeare's farewell, disguised as an island.","On an actual island if possible."),
B("Frankenstein","Mary Shelley","England",1818,"Classics","c","A teenager invented science fiction on a rainy dare.","A stormy night, obviously."),
B("Dracula","Bram Stoker","Ireland",1897,"Classics","c","The epistolary thriller that never died.","In October, letters-first pacing."),
B("The Picture of Dorian Gray","Oscar Wilde","Ireland",1890,"Classics","c","Wilde's one novel, sharp enough to shave with.","Underline the epigrams."),
B("Heart of Darkness","Joseph Conrad","Poland/England",1899,"Classics","u","A river journey into the empire's rot.","Paired with a documentary on Congo."),
B("The Count of Monte Cristo","Alexandre Dumas","France",1844,"Classics","c","The revenge plot all others photocopy.","A week of pure momentum."),
B("Les Misérables","Victor Hugo","France",1862,"Classics","r","France entire, plus fifty pages on sewers.","Unabridged or not at all."),
B("Madame Bovary","Gustave Flaubert","France",1856,"Classics","u","Every word chosen like evidence.","Slowly; Flaubert took five years."),
B("The Stranger","Albert Camus","France/Algeria",1942,"Classics","c","Begins with the most famous shrug in literature.","One hot afternoon."),
B("The Plague","Albert Camus","France/Algeria",1947,"Classics","u","A quarantine manual disguised as a novel.","You lived it; now read it."),
B("The Trial","Franz Kafka","Czechia",1925,"Classics","u","Arrested for nothing; guilty of everything.","During any bureaucratic ordeal."),
B("The Metamorphosis","Franz Kafka","Czechia",1915,"Classics","c","Wakes up a bug; the family is the horror.","One sitting, breakfast optional."),
B("The Castle","Franz Kafka","Czechia",1926,"Classics","r","Unfinished, like all appeals to authority.","Accept there's no arrival."),
B("One Hundred Years of Solitude","Gabriel García Márquez","Colombia",1967,"Classics","u","A family tree struck by lightning, repeatedly.","Keep the genealogy bookmark."),
B("Love in the Time of Cholera","Gabriel García Márquez","Colombia",1985,"Classics","u","Fifty-one years of waiting, dignified into art.","On a slow boat, ideally."),
B("Lolita","Vladimir Nabokov","Russia/USA",1955,"Classics","r","The most beautiful prose about the ugliest narrator.","Trust nothing Humbert says."),
B("Pale Fire","Vladimir Nabokov","Russia/USA",1962,"Classics","r","A poem, a commentary, and a madman between them.","Twice — the second read is the book."),
B("Brave New World","Aldous Huxley","England",1932,"Classics","c","The dystopia that seduces instead of stomping.","Alongside 1984, as a debate."),
B("Catch-22","Joseph Heller","USA",1961,"Classics","u","Gave sanity's trap its permanent name.","Laugh, then notice you're crying."),
B("Slaughterhouse-Five","Kurt Vonnegut","USA",1969,"Classics","c","Dresden burns; time gives up. So it goes.","An afternoon, unstuck."),
B("The Catcher in the Rye","J.D. Salinger","USA",1951,"Classics","c","Adolescence, patented.","At 16, and again to check on Holden."),
B("Of Mice and Men","John Steinbeck","USA",1937,"Classics","c","Tell me about the rabbits, George.","One evening; brace for the last page."),
B("The Grapes of Wrath","John Steinbeck","USA",1939,"Classics","u","Dust, dignity, and the road west.","With the Woody Guthrie songbook."),
B("East of Eden","John Steinbeck","USA",1952,"Classics","u","Cain and Abel, replanted in California.","The word is timshel. Watch for it."),
B("For Whom the Bell Tolls","Ernest Hemingway","USA",1940,"Classics","u","Three days in a war, a lifetime in a sleeping bag.","Feel the ground; that's the style."),
B("The Old Man and the Sea","Ernest Hemingway","USA",1952,"Classics","c","Eighty pages that won the Nobel.","One sitting, by water."),
B("A Farewell to Arms","Ernest Hemingway","USA",1929,"Classics","u","Love in wartime, rain forever after.","With the alternate endings appendix."),
B("Mrs Dalloway","Virginia Woolf","England",1925,"Classics","r","One London day, consciousness fully wired.","Follow the chiming of Big Ben."),
B("To the Lighthouse","Virginia Woolf","England",1927,"Classics","r","Time passes; a stocking is knitted; everything changes.","The middle section, twice."),
B("The Sound and the Fury","William Faulkner","USA",1929,"Classics","r","Four narrators, one family's fall, zero mercy.","Push through Benjy; trust Dilsey."),
B("As I Lay Dying","William Faulkner","USA",1930,"Classics","r","Fifty-nine chapters to bury one mother.","My mother is a fish. Continue."),
B("Invisible Man","Ralph Ellison","USA",1952,"Classics","u","The great American novel about being unseen.","The battle royal chapter, carefully."),
B("Beloved","Toni Morrison","USA",1987,"Classics","u","A haunted house where the ghost is history.","Sit with it; don't binge it."),
B("Song of Solomon","Toni Morrison","USA",1977,"Classics","u","A man learns to fly by learning his name.","With the family tree sketched."),
B("Their Eyes Were Watching God","Zora Neale Hurston","USA",1937,"Classics","u","A woman's voice the canon tried to lose.","Hear the dialect; it's music."),
B("The Age of Innocence","Edith Wharton","USA",1920,"Classics","u","New York society, knives out, gloves on.","With opera in the background."),
B("A Passage to India","E.M. Forster","England",1924,"Classics","u","The Raj on trial in the Marabar caves.","Alongside an Indian history primer."),
B("Rebecca","Daphne du Maurier","England",1938,"Classics","c","The dead wife wins every scene she isn't in.","Dreamt I went to Manderley: begin."),
B("Lord of the Flies","William Golding","England",1954,"Classics","c","Boys, an island, and the thin skin of civilization.","Then argue: nature or nurture?"),
B("A Clockwork Orange","Anthony Burgess","England",1962,"Classics","r","Violence in an invented slang you'll catch by page 40.","With the glossary, droog."),
B("The Master and Margarita","Mikhail Bulgakov","Russia",1967,"Classics","r","The Devil visits Moscow; the cat has a gun.","Manuscripts don't burn. Believe it."),
B("Doctor Zhivago","Boris Pasternak","Russia",1957,"Classics","u","A love story the revolution kept interrupting.","In deep winter."),
B("Fathers and Sons","Ivan Turgenev","Russia",1862,"Classics","u","Invented the nihilist, then grieved him.","Before arguing with your parents."),
B("Dead Souls","Nikolai Gogol","Russia",1842,"Classics","r","A conman buys dead serfs; Russia laughs, then flinches.","With Gogol's nose for absurdity."),
B("Eugene Onegin","Alexander Pushkin","Russia",1833,"Verse & Stage","r","A novel in verse; Russia's whole heart in stanzas.","A verse translation, aloud."),
B("The Cherry Orchard","Anton Chekhov","Russia",1904,"Verse & Stage","u","An estate sold, an era closed, an axe offstage.","Then his short stories."),
B("Waiting for Godot","Samuel Beckett","Ireland",1953,"Verse & Stage","u","Nothing happens, twice, perfectly.","With a friend; take parts."),
B("The Death of Ivan Ilyich","Leo Tolstoy","Russia",1886,"Classics","u","Dying done honestly for the first time in print.","One evening; changes the next day."),
B("Candide","Voltaire","France",1759,"Classics","u","Optimism, flogged through every continent.","Fast — it's a sprint of a satire."),
B("Gulliver's Travels","Jonathan Swift","Ireland",1726,"Classics","u","A travel book that bites every hand.","Skip no voyage; the fourth stings."),
B("Robinson Crusoe","Daniel Defoe","England",1719,"Classics","u","The original desert island fantasy, receipts included.","Then question the Friday chapters."),
B("The Scarlet Letter","Nathaniel Hawthorne","USA",1850,"Classics","u","One letter, worn until it meant something else.","After the custom-house intro, it flies."),
B("Walden","Henry David Thoreau","USA",1854,"Classics","u","Two years by a pond, invoiced to civilization.","A chapter per quiet morning."),
B("Leaves of Grass","Walt Whitman","USA",1855,"Verse & Stage","r","One poet containing multitudes, revised for 40 years.","Outdoors, at full volume."),
B("The Complete Sherlock Holmes","Arthur Conan Doyle","Scotland",1927,"Mystery & Noir","c","The consulting detective all others consult.","Foggy nights, two stories at a time."),
B("The Strange Case of Dr Jekyll and Mr Hyde","Robert Louis Stevenson","Scotland",1886,"Classics","c","The double life, given its permanent names.","One sitting; it's a novella."),
B("Treasure Island","Robert Louis Stevenson","Scotland",1883,"Classics","c","Drew the map every adventure follows.","Aloud, with voices."),
B("Siddhartha","Hermann Hesse","Germany",1922,"Classics","c","A river teaches what the Buddha couldn't.","By moving water."),
B("Steppenwolf","Hermann Hesse","Germany",1927,"Classics","r","The magic theatre: price of admission, your mind.","In a lonely stretch; it meets you there."),
B("The Magic Mountain","Thomas Mann","Germany",1924,"Classics","l","Seven years in a sanatorium; Europe diagnosed.","A long convalescence of a read."),
B("Buddenbrooks","Thomas Mann","Germany",1901,"Classics","r","Four generations of decline, immaculately kept books.","Family saga pace: no hurry."),
B("All Quiet on the Western Front","Erich Maria Remarque","Germany",1929,"Classics","c","The trench war from inside the boots.","Before any war movie."),
B("The Tin Drum","Günter Grass","Germany",1959,"Classics","r","A boy stops growing; Germany can't stop.","Drumbeat chapters; take breaks."),
B("Blood Meridian","Cormac McCarthy","USA",1985,"Classics","r","The Western, scalped of every myth.","The Judge will follow you out."),
B("The Road","Cormac McCarthy","USA",2006,"Modern & Contemporary","c","Father, son, ash, and the fire we carry.","One gray day; hug someone after."),
B("Things Fall Apart","Chinua Achebe","Nigeria",1958,"Classics","u","The empire writes back, first and hardest.","With the proverbs read twice."),
// ---- MODERN & CONTEMPORARY ----
B("Infinite Jest","David Foster Wallace","USA",1996,"Modern & Contemporary","l","1,079 pages, 388 endnotes, one tennis academy.","Two bookmarks. Endnotes are mandatory."),
B("Gravity's Rainbow","Thomas Pynchon","USA",1973,"Modern & Contemporary","l","A rocket's arc over the entire 20th century.","A reading group and a strong will."),
B("2666","Roberto Bolaño","Chile",2004,"Modern & Contemporary","l","Five novels orbiting one desert of crimes.","Part four slowly; it's the abyss."),
B("The Recognitions","William Gaddis","USA",1955,"Modern & Contemporary","l","The original cult doorstopper on forgery and faith.","Let the dialogue teach you its rules."),
B("A Suitable Boy","Vikram Seth","India",1993,"India","l","1,349 pages; four families; one groom to find.","A whole monsoon."),
B("Underworld","Don DeLillo","USA",1997,"Modern & Contemporary","r","A baseball connects fifty years of America.","The prologue alone is a masterclass."),
B("White Noise","Don DeLillo","USA",1985,"Modern & Contemporary","u","The airborne toxic event of modern life.","In a supermarket parking lot."),
B("Midnight's Children","Salman Rushdie","India",1981,"India","r","Born at midnight, August 15, 1947 — with 1,000 siblings.","Alongside a Partition history."),
B("The Satanic Verses","Salman Rushdie","India",1988,"Modern & Contemporary","r","The novel that became a geopolitical event.","Read what caused it all, calmly."),
B("The Remains of the Day","Kazuo Ishiguro","England",1989,"Modern & Contemporary","u","A butler's dignity, examined until it breaks.","Quiet evenings; the restraint is the plot."),
B("Never Let Me Go","Kazuo Ishiguro","England",2005,"Modern & Contemporary","c","A boarding school with one terrible purpose.","Unspoiled. Tell no one anything."),
B("Norwegian Wood","Haruki Murakami","Japan",1987,"Modern & Contemporary","c","The Murakami without magic — just grief and vinyl.","With the Beatles playing."),
B("The Wind-Up Bird Chronicle","Haruki Murakami","Japan",1994,"Modern & Contemporary","u","A missing cat opens a well into history.","Sit in the well; don't rush out."),
B("Kafka on the Shore","Haruki Murakami","Japan",2002,"Modern & Contemporary","u","Fish rain, talking cats, Oedipus in Takamatsu.","Accept everything; explain nothing."),
B("1Q84","Haruki Murakami","Japan",2009,"Modern & Contemporary","r","Two moons over Tokyo, three volumes over you.","A month of nights."),
B("Atonement","Ian McEwan","England",2001,"Modern & Contemporary","u","One lie in 1935; the whole century pays.","The last ten pages rewire the rest."),
B("The Corrections","Jonathan Franzen","USA",2001,"Modern & Contemporary","u","One last Christmas, one American family autopsy.","Around your own family holidays."),
B("A Little Life","Hanya Yanagihara","USA",2015,"Modern & Contemporary","r","Friendship as life support, over 700 unsparing pages.","With breaks. Seriously, with breaks."),
B("The Goldfinch","Donna Tartt","USA",2013,"Modern & Contemporary","u","A bomb, a painting, and a boy who keeps both.","A holiday week; it's a companion."),
B("The Secret History","Donna Tartt","USA",1992,"Modern & Contemporary","c","The murder is on page one; the why takes 500.","In autumn, among old buildings."),
B("Middlesex","Jeffrey Eugenides","USA",2002,"Modern & Contemporary","u","Three generations carried by one gene.","Detroit chapters with the radio on."),
B("The Amazing Adventures of Kavalier & Clay","Michael Chabon","USA",2000,"Modern & Contemporary","u","Comic books, escape artistry, and the war at home.","With a golden-age comic beside it."),
B("Cloud Atlas","David Mitchell","England",2004,"Modern & Contemporary","u","Six nested stories, one soul, centuries apart.","Trust the structure; it closes."),
B("Wolf Hall","Hilary Mantel","England",2009,"Modern & Contemporary","r","Cromwell thinks; England changes.","'He' is Cromwell. Always Cromwell."),
B("Bring Up the Bodies","Hilary Mantel","England",2012,"Modern & Contemporary","r","Anne Boleyn's fall, engineered in present tense.","Straight after Wolf Hall."),
B("Life of Pi","Yann Martel","Canada",2001,"Modern & Contemporary","c","A boy, a boat, a tiger, and two versions of truth.","Pick your story at the end."),
B("The Handmaid's Tale","Margaret Atwood","Canada",1985,"Modern & Contemporary","c","Gilead, filed under speculative; check the citations.","Then the historical notes epilogue."),
B("Oryx and Crake","Margaret Atwood","Canada",2003,"Modern & Contemporary","u","The apocalypse, brought to you by a biotech catalog.","With the news open beside it."),
B("Disgrace","J.M. Coetzee","South Africa",1999,"Modern & Contemporary","r","Post-apartheid reckoning in 220 exact pages.","In two sittings; it's merciless."),
B("Waiting for the Barbarians","J.M. Coetzee","South Africa",1980,"Modern & Contemporary","r","Empire's frontier, conscience included.","With Cavafy's poem first."),
B("The English Patient","Michael Ondaatje","Sri Lanka/Canada",1992,"Modern & Contemporary","u","Four broken people, one villa, maps of skin.","Slowly; it's written like poetry."),
B("The Sense of an Ending","Julian Barnes","England",2011,"Modern & Contemporary","u","Memory, corrected by a letter forty years late.","One sitting, then reread chapter one."),
B("Trainspotting","Irvine Welsh","Scotland",1993,"Modern & Contemporary","r","Edinburgh's underbelly in full phonetic Scots.","Hear it in the accent; it clicks."),
B("The Wasp Factory","Iain Banks","Scotland",1984,"Modern & Contemporary","r","A debut so dark reviewers quoted their own disgust.","Not before bed."),
B("Shuggie Bain","Douglas Stuart","Scotland",2020,"Modern & Contemporary","u","Glasgow, gin, and a boy who won't stop loving.","With something warm to drink."),
B("Normal People","Sally Rooney","Ireland",2018,"Modern & Contemporary","c","Two people, one decade, every almost.","In two days; everyone does."),
B("Milkman","Anna Burns","Ireland",2018,"Modern & Contemporary","r","The Troubles, told entirely without names.","Let the voice carry you; don't fight it."),
B("The Gathering","Anne Enright","Ireland",2007,"Modern & Contemporary","u","An Irish wake excavates a family secret.","With patience for grief's logic."),
B("Brooklyn","Colm Tóibín","Ireland",2009,"Modern & Contemporary","c","One woman, two shores, one impossible choice.","Before or after emigrating."),
B("The Underground Railroad","Colson Whitehead","USA",2016,"Modern & Contemporary","u","The metaphor made literal: rails under the South.","With a map of the real routes after."),
B("The Nickel Boys","Colson Whitehead","USA",2019,"Modern & Contemporary","u","A reform school's graves, given names.","Then read about Dozier. It's real."),
B("Americanah","Chimamanda Ngozi Adichie","Nigeria",2013,"Modern & Contemporary","u","Race, hair, and love across three continents.","With the blog posts savored."),
B("Half of a Yellow Sun","Chimamanda Ngozi Adichie","Nigeria",2006,"Modern & Contemporary","u","Biafra, remembered through two sisters.","With tissues and a history tab open."),
B("Homegoing","Yaa Gyasi","Ghana/USA",2016,"Modern & Contemporary","u","Two sisters, eight generations, one wound.","One chapter per generation, slowly."),
B("Pachinko","Min Jin Lee","South Korea/USA",2017,"Modern & Contemporary","u","Four generations of Koreans Japan wouldn't claim.","History first line: read it twice."),
B("A Fine Balance","Rohinton Mistry","India",1995,"India","r","The Emergency, stitched through four small lives.","Brace yourself; it doesn't blink."),
B("The White Tiger","Aravind Adiga","India",2008,"India","c","A driver writes the Premier of China the truth.","In Balram's voice, cynical and quick."),
B("The Inheritance of Loss","Kiran Desai","India",2006,"India","u","Kalimpong and Manhattan, both losing something.","With Darjeeling in the cup."),
B("The Namesake","Jhumpa Lahiri","India/USA",2003,"India","c","A name carries two continents.","Then call your parents."),
B("Interpreter of Maladies","Jhumpa Lahiri","India/USA",1999,"India","u","Nine stories, one Pulitzer, zero wasted words.","One story per evening."),
B("Sacred Games","Vikram Chandra","India",2006,"India","r","Mumbai cops and dons across 900 pages.","With the glossary of Bambaiyya."),
B("Shantaram","Gregory David Roberts","Australia/India",2003,"India","u","An escaped convict falls for Bombay, hard.","In Colaba, ideally at Leopold's."),
B("Maximum City","Suketu Mehta","India",2004,"India","r","Bombay found, lost, and interrogated.","Before and after living in Mumbai."),
B("The Palace of Illusions","Chitra Banerjee Divakaruni","India",2008,"India","c","The Mahabharata, finally in Draupadi's voice.","After knowing the original's outline."),
B("Train to Pakistan","Khushwant Singh","India",1956,"India","u","Partition arrives at one village by rail.","In one sitting; it's compact and total."),
B("Malgudi Days","R.K. Narayan","India",1943,"India","c","An invented town realer than most real ones.","Two stories with morning chai."),
B("The Guide","R.K. Narayan","India",1958,"India","u","A tour guide accidentally becomes a saint.","Then watch the Dev Anand film."),
B("Godaan","Munshi Premchand","India",1936,"India","r","The Indian peasant's ledger of debt and dignity.","In Hindi if you can; slowly if not."),
B("Raag Darbari","Shrilal Shukla","India",1968,"India","r","Village politics, satirized beyond repair.","With someone who'll get the jokes."),
B("The Discovery of India","Jawaharlal Nehru","India",1946,"India","r","A nation imagined from a prison cell.","A chapter at a time, with maps."),
B("India After Gandhi","Ramachandra Guha","India",2007,"India","r","The republic's biography, 900 pages of receipts.","A monsoon project; worth every page."),
B("The Argumentative Indian","Amartya Sen","India",2005,"India","r","India's long tradition of talking back.","Essays out of order, as arguments arise."),
B("Em and the Big Hoom","Jerry Pinto","India",2012,"India","u","A mother's madness, a family's arithmetic of love.","With your own family in mind."),
B("Ghachar Ghochar","Vivek Shanbhag","India",2015,"India","u","New money tangles one Bangalore family.","One sitting; the title will make sense."),
B("Tomb of Sand","Geetanjali Shree","India",2018,"India","r","An 80-year-old crosses the border of grief.","In Daisy Rockwell's translation."),
B("Karukku","Bama","India",1992,"India","r","Dalit life, told plainly and unforgettably.","With humility; listen, don't judge."),
B("The Great Indian Novel","Shashi Tharoor","India",1989,"India","u","The Mahabharata recast as the freedom struggle.","With both histories half-remembered."),
// ---- WORLD ----
B("The Tale of Genji","Murasaki Shikibu","Japan",1010,"World","l","The world's first novel, by a court lady, 1,000 years old.","A seasons-long pilgrimage."),
B("The Man Without Qualities","Robert Musil","Austria",1930,"World","l","Vienna, 1913: an empire thinks itself to death.","Unfinished by design; so is life."),
B("The Book of Disquiet","Fernando Pessoa","Portugal",1982,"World","r","A diary of a man who was four writers.","Random pages, like weather."),
B("Blindness","José Saramago","Portugal",1995,"World","r","A city goes blind; punctuation goes with it.","Let the commas carry you."),
B("The Name of the Rose","Umberto Eco","Italy",1980,"World","u","A monastery murder wrapped in medieval philosophy.","Push through the door; treasure inside."),
B("If on a winter's night a traveler","Italo Calvino","Italy",1979,"World","r","A novel about you, reading this novel.","Exactly as it instructs you to."),
B("Invisible Cities","Italo Calvino","Italy",1972,"World","r","Marco Polo describes 55 cities; all are Venice.","One city per night."),
B("My Brilliant Friend","Elena Ferrante","Italy",2011,"World","u","Naples, two girls, sixty years of ferocity begins.","Commit to all four; it's one book."),
B("The Leopard","Giuseppe Tomasi di Lampedusa","Italy",1958,"World","r","Sicily's aristocracy watches itself set.","For things to stay the same… read on."),
B("The Shadow of the Wind","Carlos Ruiz Zafón","Spain",2001,"World","c","A cemetery of forgotten books; one boy's rescue.","In Barcelona's old town, if you can."),
B("Pedro Páramo","Juan Rulfo","Mexico",1955,"World","r","A town of whispers; the dead never left.","Twice — García Márquez read it aloud."),
B("The House of the Spirits","Isabel Allende","Chile",1982,"World","u","Four generations, one country's coup.","With Chile's history at elbow."),
B("Ficciones","Jorge Luis Borges","Argentina",1944,"World","r","Infinite libraries, forking paths, 17 perfect stories.","One story, then a walk to recover."),
B("Hopscotch","Julio Cortázar","Argentina",1963,"World","r","A novel you can read in two different orders.","Both orders. Obviously."),
B("The Aleph","Jorge Luis Borges","Argentina",1949,"World","r","Every point in the universe, under a Buenos Aires stair.","Slowly, with a notebook."),
B("The Savage Detectives","Roberto Bolaño","Chile",1998,"World","r","Poets hunt a poet across decades and deserts.","With the visceral realists' energy."),
B("Snow Country","Yasunari Kawabata","Japan",1948,"World","r","A hot spring affair, written in haiku prose.","In winter, near a window."),
B("Kokoro","Natsume Sōseki","Japan",1914,"World","u","A student, a master, and Japan's turning heart.","With green tea, unhurried."),
B("The Makioka Sisters","Jun'ichirō Tanizaki","Japan",1948,"World","r","Four sisters, one Osaka world about to vanish.","Family-saga pace, cherry-blossom slow."),
B("Convenience Store Woman","Sayaka Murata","Japan",2016,"World","c","A woman perfectly calibrated to a konbini.","One sitting; smile uneasily."),
B("Kitchen","Banana Yoshimoto","Japan",1988,"World","c","Grief cooked down to something bearable.","With something simmering."),
B("The Vegetarian","Han Kang","South Korea",2007,"World","u","One refusal; a family detonates.","In three sittings, one per act."),
B("Please Look After Mom","Kyung-sook Shin","South Korea",2008,"World","u","A mother lost in a subway; a family found out.","Then call yours."),
B("Red Sorghum","Mo Yan","China",1986,"World","r","Three generations distilled in sorghum wine and war.","With strong drink nearby."),
B("To Live","Yu Hua","China",1993,"World","u","One man survives every decade China throws.","One evening; it's lean and total."),
B("Dream of the Red Chamber","Cao Xueqin","China",1791,"World","l","China's greatest novel; a garden of 400 characters.","With a character index and a year."),
B("The Three-Body Problem","Liu Cixin","China",2008,"SF & Fantasy","u","Physics breaks; the reason is watching.","Nights; look up at the stars after."),
B("Season of Migration to the North","Tayeb Salih","Sudan",1966,"World","r","Colonialism's current, reversed up the Nile.","Paired with Heart of Darkness."),
B("So Long a Letter","Mariama Bâ","Senegal",1979,"World","r","A widow's letter that carries a continent.","One quiet afternoon."),
B("The Cairo Trilogy","Naguib Mahfouz","Egypt",1957,"World","r","Three generations in one Cairo alley; a Nobel earned.","One volume per month."),
B("Men in the Sun","Ghassan Kanafani","Palestine",1963,"World","r","Three men, one water tank, the Palestinian century.","One sitting; the knock stays with you."),
B("My Name Is Red","Orhan Pamuk","Türkiye",1998,"World","r","A murder among Ottoman miniaturists; color testifies.","Slow; let each narrator paint."),
B("Snow","Orhan Pamuk","Türkiye",2002,"World","r","A poet returns; Kars closes with the snow.","In winter, naturally."),
B("The Forty Rules of Love","Elif Shafak","Türkiye",2009,"World","c","Rumi and Shams, braided with a Boston housewife.","With Rumi's ghazals after."),
B("Persepolis","Marjane Satrapi","Iran",2000,"Lives & Journeys","c","A girlhood in the revolution, in black and white.","One evening; it's a graphic memoir."),
B("The Blind Owl","Sadegh Hedayat","Iran",1936,"World","r","Iran's darkest masterpiece; approach with care.","Daylight hours recommended."),
B("The Unbearable Lightness of Being","Milan Kundera","Czechia",1984,"World","u","Love and tanks in Prague, weighed against nothing.","With the Nietzsche intro re-read."),
B("Too Loud a Solitude","Bohumil Hrabal","Czechia",1976,"World","r","A book-crusher who saves what he pulps.","One sitting, beer in hand."),
B("The Good Soldier Švejk","Jaroslav Hašek","Czechia",1923,"World","r","Idiocy as resistance; the empire never recovers.","In a pub, laughing audibly."),
B("Solaris","Stanisław Lem","Poland",1961,"SF & Fantasy","r","An ocean that thinks; grief given a planet.","Then both film versions."),
B("The Books of Jacob","Olga Tokarczuk","Poland",2014,"World","l","A false messiah crosses 18th-century Europe; pages count backward.","A season; trust the current."),
B("Drive Your Plow Over the Bones of the Dead","Olga Tokarczuk","Poland",2009,"World","u","An astrologer investigates; the animals have motives.","On winter nights."),
B("Death and the Penguin","Andrey Kurkov","Ukraine",1996,"World","u","An obituarist and his penguin outlive their subjects.","With dark laughter permitted."),
B("Life and Fate","Vasily Grossman","Russia",1960,"World","l","Stalingrad's War and Peace; the KGB arrested the manuscript.","A long winter; it earns the name."),
B("One Day in the Life of Ivan Denisovich","Aleksandr Solzhenitsyn","Russia",1962,"World","u","One gulag day, measured in bread grams.","One cold day, gratefully."),
B("The Gulag Archipelago","Aleksandr Solzhenitsyn","Russia",1973,"World","l","The archipelago mapped; the century indicted.","The abridged edition counts."),
B("Out Stealing Horses","Per Petterson","Norway",2003,"World","u","A Norwegian summer returns, sixty years later.","In a cabin, ideally."),
B("Smilla's Sense of Snow","Peter Høeg","Denmark",1992,"Mystery & Noir","u","A Greenlander reads snow like evidence.","In deep winter."),
B("The Emigrants","W.G. Sebald","Germany",1992,"World","r","Four lives, photographs included, grief unphotographed.","Slowly; the images are load-bearing."),
B("Austerlitz","W.G. Sebald","Germany",2001,"World","r","A man discovers his own history at a train station.","One long unbroken attention."),
B("Beware of Pity","Stefan Zweig","Austria",1939,"World","r","Pity mistaken for love; empire-grade consequences.","In two feverish evenings."),
B("The Radetzky March","Joseph Roth","Austria",1932,"World","r","Three generations salute an empire dissolving.","With a waltz playing once."),
B("Independent People","Halldór Laxness","Iceland",1934,"World","r","One stubborn sheep farmer versus everything.","In the bleak midwinter, with coffee."),
// ---- SF & FANTASY ----
B("Dune","Frank Herbert","USA",1965,"SF & Fantasy","u","Ecology, prophecy, and spice: SF's great cathedral.","Before any adaptation."),
B("The Lord of the Rings","J.R.R. Tolkien","England",1954,"SF & Fantasy","u","The map every fantasy still walks.","A winter, unabridged, appendices too."),
B("The Hobbit","J.R.R. Tolkien","England",1937,"SF & Fantasy","c","There and back again; the door to everything.","Aloud, with a fire."),
B("A Game of Thrones","George R.R. Martin","USA",1996,"SF & Fantasy","c","Winter was coming before it was television.","Knowing the show spoils nothing real."),
B("The Name of the Wind","Patrick Rothfuss","USA",2007,"SF & Fantasy","c","A legend narrates himself, beautifully unreliably.","Accept the wait for book three."),
B("The Left Hand of Darkness","Ursula K. Le Guin","USA",1969,"SF & Fantasy","r","Gender dissolved on a planet of ice.","The ice crossing chapters, twice."),
B("A Wizard of Earthsea","Ursula K. Le Guin","USA",1968,"SF & Fantasy","u","Magic as true names; shadow as self.","Before Harry Potter, ideally."),
B("The Dispossessed","Ursula K. Le Guin","USA",1974,"SF & Fantasy","r","Two worlds, one wall, an ambiguous utopia.","With your politics loosened."),
B("Foundation","Isaac Asimov","USA",1951,"SF & Fantasy","u","Psychohistory: predicting the fall of empires.","The original trilogy straight through."),
B("I, Robot","Isaac Asimov","USA",1950,"SF & Fantasy","c","Three laws; a century of loopholes.","One story per commute."),
B("2001: A Space Odyssey","Arthur C. Clarke","England",1968,"SF & Fantasy","u","The monolith explained — Kubrick kept it silent.","After the film, for answers."),
B("Rendezvous with Rama","Arthur C. Clarke","England",1973,"SF & Fantasy","u","An empty alien ship; wonder needs no villain.","In silence, like Rama itself."),
B("Neuromancer","William Gibson","USA",1984,"SF & Fantasy","r","Cyberspace, coined here before the internet mattered.","Let the slang wash over; it compiles."),
B("Snow Crash","Neal Stephenson","USA",1992,"SF & Fantasy","u","The metaverse, pizza delivery, and a katana.","Fast; it's built for velocity."),
B("Hyperion","Dan Simmons","USA",1989,"SF & Fantasy","r","Canterbury Tales in space; the Shrike waits.","The priest's tale will hook you."),
B("Ender's Game","Orson Scott Card","USA",1985,"SF & Fantasy","c","Children's games with genocidal stakes.","Then argue about the ending."),
B("The Hitchhiker's Guide to the Galaxy","Douglas Adams","England",1979,"SF & Fantasy","c","Don't panic; bring a towel.","Aloud, badly, laughing."),
B("Good Omens","Terry Pratchett & Neil Gaiman","England",1990,"SF & Fantasy","c","The apocalypse, mislaid by an angel and a demon.","With footnotes read religiously."),
B("Small Gods","Terry Pratchett","England",1992,"SF & Fantasy","u","A god reduced to a tortoise; belief examined.","Any Discworld door works; this one's best."),
B("American Gods","Neil Gaiman","England",2001,"SF & Fantasy","u","Old gods work gas stations in the Midwest.","On a road trip."),
B("Jonathan Strange & Mr Norrell","Susanna Clarke","England",2004,"SF & Fantasy","r","English magic returns, with 200 footnotes.","A winter; the footnotes are the feast."),
B("Piranesi","Susanna Clarke","England",2020,"SF & Fantasy","u","An infinite house, a faithful resident, a mystery.","Unspoiled, in two sittings."),
B("The Fifth Season","N.K. Jemisin","USA",2015,"SF & Fantasy","r","The earth fights back; three Hugos in a row began here.","Trust the second person; it pays."),
B("Children of Time","Adrian Tchaikovsky","England",2015,"SF & Fantasy","u","Uplifted spiders inherit the earth — and deserve it.","Arachnophobes: push through anyway."),
B("The Martian","Andy Weir","USA",2011,"SF & Fantasy","c","Stranded on Mars with potatoes and profanity.","In one weekend of cheering."),
B("Project Hail Mary","Andy Weir","USA",2021,"SF & Fantasy","c","Amnesia, aliens, and the friendship of the decade.","Unspoiled. Question. Answer."),
B("Kindred","Octavia E. Butler","USA",1979,"SF & Fantasy","r","Time travel with no romance: straight to a plantation.","In one shaken weekend."),
B("Parable of the Sower","Octavia E. Butler","USA",1993,"SF & Fantasy","r","2024, written in 1993, uncomfortably accurately.","With the sequel ready."),
B("Fahrenheit 451","Ray Bradbury","USA",1953,"SF & Fantasy","c","Firemen burn books; a classic that stays lit.","In paper, pointedly."),
B("The Martian Chronicles","Ray Bradbury","USA",1950,"SF & Fantasy","u","Mars as America's mirror, in linked elegies.","One chronicle per night."),
B("Do Androids Dream of Electric Sheep?","Philip K. Dick","USA",1968,"SF & Fantasy","u","Empathy tested; humanity flunks.","Before rewatching Blade Runner."),
B("Ubik","Philip K. Dick","USA",1969,"SF & Fantasy","r","Reality decays; a spray can might save you.","Accept confusion as the plot."),
B("Roadside Picnic","Arkady & Boris Strugatsky","Russia",1972,"SF & Fantasy","r","Aliens stopped, littered, left; we worship the trash.","Then Tarkovsky's Stalker."),
// ---- MYSTERY & NOIR ----
B("And Then There Were None","Agatha Christie","England",1939,"Mystery & Noir","c","Ten strangers, one island, the best-selling mystery ever.","One stormy evening, all of it."),
B("Murder on the Orient Express","Agatha Christie","England",1934,"Mystery & Noir","c","The solution everyone knows and still gasps at.","On a train if fate allows."),
B("The Big Sleep","Raymond Chandler","USA",1939,"Mystery & Noir","u","Marlowe walks the mean streets; similes get hurt.","With whiskey and rain."),
B("The Long Goodbye","Raymond Chandler","USA",1953,"Mystery & Noir","r","Chandler's saddest, deepest case.","Slowly; it's a friendship autopsy."),
B("The Maltese Falcon","Dashiell Hammett","USA",1930,"Mystery & Noir","u","The stuff dreams are made of, in hardboiled prose.","Then Bogart, immediately."),
B("The Talented Mr. Ripley","Patricia Highsmith","USA",1955,"Mystery & Noir","u","You'll root for the murderer. That's the trick.","On an Italian holiday, uneasily."),
B("Strangers on a Train","Patricia Highsmith","USA",1950,"Mystery & Noir","u","Two murders, swapped like train seats.","Then Hitchcock's version."),
B("In Cold Blood","Truman Capote","USA",1966,"Mystery & Noir","u","The nonfiction novel, invented over four Kansas graves.","With the ethics debate after."),
B("The Girl with the Dragon Tattoo","Stieg Larsson","Sweden",2005,"Mystery & Noir","c","A locked island, a cold case, and Lisbeth Salander.","A dark weekend, all three books."),
B("Gone Girl","Gillian Flynn","USA",2012,"Mystery & Noir","c","The cool girl monologue alone earns the shelf.","Unspoiled if you somehow still are."),
B("The Silence of the Lambs","Thomas Harris","USA",1988,"Mystery & Noir","u","Lecter speaks; the genre reorganizes.","Before bed is a mistake."),
B("The Day of the Jackal","Frederick Forsyth","England",1971,"Mystery & Noir","u","An assassination we know fails, unbearably tense anyway.","One long-haul flight."),
B("Tinker Tailor Soldier Spy","John le Carré","England",1974,"Mystery & Noir","r","The mole hunt, played entirely in gray.","Take notes; Smiley would."),
B("The Spy Who Came in from the Cold","John le Carré","England",1963,"Mystery & Noir","u","The Cold War's conscience, in 240 pages.","One cold sitting."),
B("L.A. Confidential","James Ellroy","USA",1990,"Mystery & Noir","r","Three cops, one massacre, LA's rotten heart.","Telegraphic style: trust it."),
B("Devil in a Blue Dress","Walter Mosley","USA",1990,"Mystery & Noir","u","Easy Rawlins works 1948 LA the maps ignore.","With jazz on."),
B("The Moonstone","Wilkie Collins","England",1868,"Mystery & Noir","r","The first detective novel; the diamond still cursed.","Serial pace, Victorian patience."),
B("The Woman in White","Wilkie Collins","England",1859,"Mystery & Noir","r","Identity theft, Victorian style, still chilling.","By candlelight for effect."),
B("The Hound of the Baskervilles","Arthur Conan Doyle","Scotland",1902,"Mystery & Noir","c","The moor, the hound, the definitive Holmes.","On a foggy night."),
B("The Secret in Their Eyes","Eduardo Sacheri","Argentina",2005,"Mystery & Noir","u","A cold case Argentina couldn't close either.","Then the Oscar-winning film."),
B("Out","Natsuo Kirino","Japan",1997,"Mystery & Noir","r","Four factory women dispose of a problem.","Not on a night shift."),
B("The Devotion of Suspect X","Keigo Higashino","Japan",2005,"Mystery & Noir","u","The alibi is the masterpiece.","One evening; the last page lands."),
B("Six Four","Hideo Yokoyama","Japan",2012,"Mystery & Noir","r","A kidnapping cold case inside police politics.","Patiently; it's a slow avalanche."),
B("My Sister, the Serial Killer","Oyinkan Braithwaite","Nigeria",2018,"Mystery & Noir","c","Lagos, bleach, and sisterhood's fine print.","Two hours, one smirk."),
B("The No. 1 Ladies' Detective Agency","Alexander McCall Smith","Botswana",1998,"Mystery & Noir","c","Precious Ramotswe opens shop; Botswana smiles.","With red bush tea."),
B("Case Histories","Kate Atkinson","England",2004,"Mystery & Noir","u","Three cold cases braid into one warm heart.","Then the rest of Brodie."),
// ---- IDEAS & SCIENCE ----
B("A Brief History of Time","Stephen Hawking","England",1988,"Ideas & Science","c","The best-selling book everyone owns and few finish.","Finish it; that's the flex."),
B("The Selfish Gene","Richard Dawkins","England",1976,"Ideas & Science","u","Genes as protagonists; 'meme' coined on the way.","Chapter by chapter, arguing."),
B("Gödel, Escher, Bach","Douglas Hofstadter","USA",1979,"Ideas & Science","l","Logic, art, and music braided into one strange loop.","A year of Sundays; do the puzzles."),
B("Thinking, Fast and Slow","Daniel Kahneman","Israel/USA",2011,"Ideas & Science","u","Your two minds, formally introduced.","With a pencil; test yourself."),
B("The Structure of Scientific Revolutions","Thomas Kuhn","USA",1962,"Ideas & Science","r","Gave 'paradigm shift' to every meeting room, correctly.","Then notice paradigms everywhere."),
B("Silent Spring","Rachel Carson","USA",1962,"Ideas & Science","u","One book started environmentalism; DDT never recovered.","With birdsong outside."),
B("The Double Helix","James Watson","USA",1968,"Ideas & Science","u","DNA's discovery, gossip included; Franklin wronged.","With the Franklin corrective after."),
B("The Emperor of All Maladies","Siddhartha Mukherjee","India/USA",2010,"Ideas & Science","r","Cancer's biography, 4,000 years of it.","In stretches; it's heavy and worth it."),
B("The Gene","Siddhartha Mukherjee","India/USA",2016,"Ideas & Science","u","Heredity's story, family history included.","After Emperor; it's the sequel."),
B("The Sixth Extinction","Elizabeth Kolbert","USA",2014,"Ideas & Science","u","The one we're causing, documented calmly.","Then look at a frog differently."),
B("Cosmos","Carl Sagan","USA",1980,"Ideas & Science","u","The universe, narrated with a poet's patience.","A chapter, then the night sky."),
B("Pale Blue Dot","Carl Sagan","USA",1994,"Ideas & Science","u","Earth from four billion miles: that's everyone.","Read the mote-of-dust passage aloud."),
B("A Short History of Nearly Everything","Bill Bryson","USA",2003,"Ideas & Science","c","Science's greatest hits, told by its funniest tourist.","Perfect commute chapters."),
B("Guns, Germs, and Steel","Jared Diamond","USA",1997,"Ideas & Science","u","Geography as destiny; empires as accidents.","Then read its critics too."),
B("The Wealth of Nations","Adam Smith","Scotland",1776,"Ideas & Science","l","The invisible hand's first appearance.","Selections count; it's a reference."),
B("Das Kapital","Karl Marx","Germany",1867,"Ideas & Science","l","The critique capitalism keeps having to answer.","Volume one; a reading group helps."),
B("The Republic","Plato","Greece",-375,"Ideas & Science","r","The cave, the philosopher-king, the whole syllabus.","With someone to argue against."),
B("Meditations","Marcus Aurelius","Rome",180,"Ideas & Science","c","A Roman emperor's private notes-to-self.","One page per morning."),
B("The Art of War","Sun Tzu","China",-500,"Ideas & Science","c","2,500 years of strategy in 13 chapters.","Then reread before any negotiation."),
B("The Prince","Niccolò Machiavelli","Italy",1532,"Ideas & Science","u","Power without perfume.","In one sitting; keep your soul on."),
B("Thus Spoke Zarathustra","Friedrich Nietzsche","Germany",1883,"Ideas & Science","r","Philosophy as scripture; the abyss gazes back.","Slowly, out loud sometimes."),
B("Beyond Good and Evil","Friedrich Nietzsche","Germany",1886,"Ideas & Science","r","Morality, cross-examined without anesthesia.","Aphorism by aphorism."),
B("Man's Search for Meaning","Viktor Frankl","Austria",1946,"Ideas & Science","c","Auschwitz survived; meaning located.","One sitting; keep it forever."),
B("The Second Sex","Simone de Beauvoir","France",1949,"Ideas & Science","r","One is not born a woman; the argument begins.","The key chapters; annotate freely."),
B("A Room of One's Own","Virginia Woolf","England",1929,"Ideas & Science","u","Five hundred pounds and a lock on the door.","In your own room, pointedly."),
B("Orientalism","Edward Said","Palestine/USA",1978,"Ideas & Science","r","How the West invented its East.","Before your next 'exotic' trip."),
B("The Wretched of the Earth","Frantz Fanon","Martinique",1961,"Ideas & Science","r","Decolonization's field manual and fever chart.","With the Sartre preface debated."),
B("Discipline and Punish","Michel Foucault","France",1975,"Ideas & Science","r","The panopticon escapes the prison.","Then notice the cameras."),
B("Homo Deus","Yuval Noah Harari","Israel",2015,"Ideas & Science","c","Tomorrow's religions: data and immortality.","Then argue with chapter one."),
B("Freakonomics","Steven Levitt & Stephen Dubner","USA",2005,"Ideas & Science","c","Incentives explain everything, including this book.","Podcast pace, chapter rides."),
B("The Black Swan","Nassim Nicholas Taleb","Lebanon/USA",2007,"Ideas & Science","u","The improbable runs the world; Wall Street flinched.","Skip nothing; endure the swagger."),
B("Antifragile","Nassim Nicholas Taleb","Lebanon/USA",2012,"Ideas & Science","u","What gains from disorder, from bones to bonds.","With your portfolio in mind."),
B("Zero to One","Peter Thiel","USA",2014,"Ideas & Science","c","Competition is for losers; the contrarian catechism.","One flight; disagree productively."),
B("The Intelligent Investor","Benjamin Graham","USA",1949,"Ideas & Science","u","Mr. Market introduced; Buffett's bible.","Chapters 8 and 20 twice."),
B("Poor Charlie's Almanack","Charlie Munger","USA",2005,"Ideas & Science","r","Mental models from Buffett's other half.","One talk per week."),
B("Thinking in Bets","Annie Duke","USA",2018,"Ideas & Science","c","Poker's decision science for everyone else.","Before your next big call."),
B("The Design of Everyday Things","Don Norman","USA",1988,"Ideas & Science","u","Why doors confuse you; it's not you.","Then push a 'pull' door knowingly."),
B("Chaos","James Gleick","USA",1987,"Ideas & Science","u","The butterfly effect gets its biography.","With the Mandelbrot images handy."),
B("The Information","James Gleick","USA",2011,"Ideas & Science","r","From talking drums to bits: information's epic.","In stretches; it's a signal-rich read."),
B("The Beginning of Infinity","David Deutsch","England",2011,"Ideas & Science","r","Explanations as the engine of everything.","Slowly; optimism this rigorous is rare."),
B("Superintelligence","Nick Bostrom","Sweden",2014,"Ideas & Science","r","The AI alignment problem, stated first and coldest.","Then follow the debate it started."),
B("Behave","Robert Sapolsky","USA",2017,"Ideas & Science","r","Why we do what we do, one second to one epoch before.","The appendix on neuroscience first."),
B("Why We Sleep","Matthew Walker","England",2017,"Ideas & Science","c","Sleep, prosecuted as the miracle drug it is.","Early, in bed, ironically."),
B("Being Mortal","Atul Gawande","USA",2014,"Ideas & Science","u","Medicine meets mortality; families should too.","Before you need it. Everyone will."),
B("When Breath Becomes Air","Paul Kalanithi","USA",2016,"Lives & Journeys","c","A neurosurgeon's diagnosis becomes his masterpiece.","One sitting; keep tissues."),
// ---- LIVES & JOURNEYS ----
B("Kitchen Confidential","Anthony Bourdain","USA",2000,"Lives & Journeys","u","Don't order fish on Mondays; a voice arrives fully formed.","Then cook something, badly, happily."),
B("A Cook's Tour","Anthony Bourdain","USA",2001,"Lives & Journeys","r","The template for eating the world honestly.","Before your next trip anywhere."),
B("Medium Raw","Anthony Bourdain","USA",2010,"Lives & Journeys","u","The sequel with scores settled and heroes named.","With the 'grandma rule' memorized."),
B("The Motorcycle Diaries","Ernesto Che Guevara","Argentina",1993,"Lives & Journeys","u","A road trip that radicalized a continent's icon.","On any long ride south."),
B("Into the Wild","Jon Krakauer","USA",1996,"Lives & Journeys","c","Alexander Supertramp walks into Alaska.","Then argue: romantic or reckless?"),
B("Into Thin Air","Jon Krakauer","USA",1997,"Lives & Journeys","u","Everest, 1996 — the account that ended innocence.","In one storm of a sitting."),
B("Wild","Cheryl Strayed","USA",2012,"Lives & Journeys","c","1,100 miles of trail as grief therapy.","Before any solo trek."),
B("A Walk in the Woods","Bill Bryson","USA",1998,"Lives & Journeys","c","The Appalachian Trail, hilariously under-prepared for.","With snacks; you'll crave them."),
B("In Patagonia","Bruce Chatwin","England",1977,"Lives & Journeys","r","Travel writing rebuilt in 97 fragments.","Non-linearly, like the journey."),
B("The Songlines","Bruce Chatwin","England",1987,"Lives & Journeys","r","Australia sung into existence; walking as writing.","On foot, some of it."),
B("Arabian Sands","Wilfred Thesiger","England",1959,"Lives & Journeys","r","The Empty Quarter crossed twice, mourned forever.","Before your own Empty Quarter night."),
B("Seven Years in Tibet","Heinrich Harrer","Austria",1952,"Lives & Journeys","u","An escapee tutors a young Dalai Lama.","With the map of the escape route."),
B("The Snow Leopard","Peter Matthiessen","USA",1978,"Lives & Journeys","r","A Himalayan trek where the cat is optional.","Slowly, like altitude."),
B("Shadow of the Silk Road","Colin Thubron","England",2006,"Lives & Journeys","r","7,000 miles of the old road, listened to.","With Uzbekistan plans forming."),
B("Full Tilt","Dervla Murphy","Ireland",1965,"Lives & Journeys","r","Dublin to Delhi by bicycle, 1963, with a pistol.","Then question your excuses."),
B("Long Walk to Freedom","Nelson Mandela","South Africa",1994,"Lives & Journeys","u","27 years distilled into grace.","In stretches; let it teach patience."),
B("The Diary of a Young Girl","Anne Frank","Netherlands",1947,"Lives & Journeys","c","Two years in the annex; the century's conscience.","Then visit the house someday."),
B("Night","Elie Wiesel","Romania/USA",1956,"Lives & Journeys","u","The Holocaust in 120 pages of ash.","One sitting; carry it after."),
B("I Know Why the Caged Bird Sings","Maya Angelou","USA",1969,"Lives & Journeys","u","A childhood survived into poetry.","Aloud where possible."),
B("Educated","Tara Westover","USA",2018,"Lives & Journeys","c","From no school to Cambridge; family as gravity.","Then call an old teacher."),
B("Born a Crime","Trevor Noah","South Africa",2016,"Lives & Journeys","c","Apartheid's absurdity via a mother's fearlessness.","The audiobook is the definitive text."),
B("The Glass Castle","Jeannette Walls","USA",2005,"Lives & Journeys","c","A nomadic childhood, loved and indicted at once.","In two evenings."),
B("Angela's Ashes","Frank McCourt","Ireland/USA",1996,"Lives & Journeys","u","A miserable Irish childhood, told with a grin.","Rain outside helps."),
B("Wild Swans","Jung Chang","China",1991,"Lives & Journeys","r","Three daughters of China across the century.","With the timeline flagged."),
B("Papillon","Henri Charrière","France",1969,"Lives & Journeys","u","Escape as a life's work.","Doubt the details; enjoy every one."),
B("Touching the Void","Joe Simpson","England",1988,"Lives & Journeys","u","Cut the rope. Then it gets worse.","One breathless evening."),
B("Endurance","Alfred Lansing","USA",1959,"Lives & Journeys","r","Shackleton loses the ship and saves every man.","In winter, gratefully warm."),
B("The Worst Journey in the World","Apsley Cherry-Garrard","England",1922,"Lives & Journeys","l","Antarctica, 1911: the title undersells it.","A polar month; earn the penguin egg."),
B("West with the Night","Beryl Markham","Kenya/England",1942,"Lives & Journeys","r","Hemingway wished he'd written it. He was right.","At dusk, with the prose glowing."),
B("Out of Africa","Isak Dinesen","Denmark/Kenya",1937,"Lives & Journeys","u","I had a farm in Africa: begin.","Slow evenings, coffee growing."),
B("Steve Jobs","Walter Isaacson","USA",2011,"Lives & Journeys","c","The reality distortion field, documented.","Then delete three apps."),
B("Shoe Dog","Phil Knight","USA",2016,"Lives & Journeys","c","Nike's origin as a debt-fueled prayer.","The best founder memoir; one weekend."),
B("Surely You're Joking, Mr. Feynman!","Richard Feynman","USA",1985,"Lives & Journeys","u","Safecracking, bongos, and Nobel physics.","One anecdote per coffee."),
B("The Right Stuff","Tom Wolfe","USA",1979,"Lives & Journeys","u","Test pilots, astronauts, and the unspoken code.","Then watch a launch."),
B("Barbarian Days","William Finnegan","USA",2015,"Lives & Journeys","r","A surfing life; the Pulitzer's best wave.","Beach reading, literally elevated."),
B("Just Kids","Patti Smith","USA",2010,"Lives & Journeys","u","Patti and Robert, broke and holy in old New York.","With Horses playing after."),
B("The Year of Magical Thinking","Joan Didion","USA",2005,"Lives & Journeys","u","Grief, reported with terrifying precision.","Not while grieving; or exactly then."),
B("Slouching Towards Bethlehem","Joan Didion","USA",1968,"Lives & Journeys","r","The sixties, x-rayed in essays.","One essay per sitting; reread the title one."),
B("Down and Out in Paris and London","George Orwell","England",1933,"Lives & Journeys","u","Dishwashing as war reporting.","Before romanticizing 'the grind'."),
B("Homage to Catalonia","George Orwell","England",1938,"Lives & Journeys","r","Orwell takes a bullet for Spain and honesty.","With the war's map open."),
// ---- MORE WORLD / CLASSICS / VERSE ----
B("The Ramayana","Valmiki","India",-500,"India","r","The exile, the abduction, the bridge of monkeys.","Any good retelling counts."),
B("The Mahabharata","Vyasa","India",-400,"India","l","The longest poem on Earth; everything is in it.","A retelling first; the epic is an era."),
B("The Bhagavad Gita","Vyasa","India",-200,"India","u","The battlefield sermon at the heart of it all.","Aloud, both doubting and believing."),
B("The Panchatantra","Vishnu Sharma","India",-300,"India","u","The fables that traveled west and became Aesop's rivals.","With a child, or your inner one."),
B("Gitanjali","Rabindranath Tagore","India",1910,"Verse & Stage","u","Song offerings; Asia's first Nobel.","One poem at dawn."),
B("The Home and the World","Rabindranath Tagore","India",1916,"India","r","Nationalism and love argue in one Bengali home.","Then Ray's film adaptation."),
B("Selected Poems","Mirza Ghalib","India",1850,"Verse & Stage","r","The ghazal's summit; grief with a wink.","With translations facing the Urdu."),
B("Madhushala","Harivansh Rai Bachchan","India",1935,"Verse & Stage","r","The tavern as philosophy, 135 quatrains deep.","Aloud, in Hindi, glass raised."),
B("Rubaiyat of Omar Khayyam","Omar Khayyam","Persia",1120,"Verse & Stage","u","A jug of wine, a loaf of bread, and eternity.","FitzGerald's version at sunset."),
B("The Masnavi","Rumi","Persia",1273,"Verse & Stage","r","The Persian Quran, as they call it; love's epic.","A few couplets at a time."),
B("Shahnameh","Ferdowsi","Persia",1010,"World","l","Persia's Book of Kings, 50,000 couplets of memory.","An illustrated selection; then more."),
B("The Thousand and One Nights","Anonymous","Middle East",800,"World","r","Scheherazade invents the cliffhanger to survive.","One night's tale per night."),
B("Beowulf","Anonymous","England",1000,"Verse & Stage","u","The monster, the mother, the dragon: English begins.","Heaney's translation, aloud."),
B("The Canterbury Tales","Geoffrey Chaucer","England",1400,"Classics","r","The pilgrimage that invented English literature's grin.","A tale per week, best bawdy ones first."),
B("Paradise Lost","John Milton","England",1667,"Verse & Stage","r","Satan gets the best lines; Milton knew.","Book One aloud; you'll continue."),
B("Faust","Johann Wolfgang von Goethe","Germany",1808,"Verse & Stage","r","The deal underlying every deal since.","Part One; Part Two if possessed."),
B("The Sorrows of Young Werther","Johann Wolfgang von Goethe","Germany",1774,"Classics","u","The novel that made Europe weep on schedule.","In one melodramatic evening."),
B("The Flowers of Evil","Charles Baudelaire","France",1857,"Verse & Stage","r","Beauty prosecuted for obscenity; beauty won.","One poem, then a city walk."),
B("Duino Elegies","Rainer Maria Rilke","Austria",1923,"Verse & Stage","r","Ten elegies; every angel is terrifying.","Slowly, over ten evenings."),
B("Letters to a Young Poet","Rainer Maria Rilke","Austria",1929,"Lives & Journeys","c","Live the questions now.","Whenever lost; it's a compass."),
B("Twenty Love Poems and a Song of Despair","Pablo Neruda","Chile",1924,"Verse & Stage","c","Tonight I can write the saddest lines.","Aloud, to someone or the sea."),
B("The Prophet","Kahlil Gibran","Lebanon",1923,"Verse & Stage","c","On love, work, children: the wedding-reading canon.","One chapter per life event."),
B("The Waste Land","T.S. Eliot","USA/England",1922,"Verse & Stage","r","April is the cruellest month; modernity fragments.","With notes, then without."),
B("Howl","Allen Ginsberg","USA",1956,"Verse & Stage","r","The best minds of a generation, at full volume.","Aloud. It was built for breath."),
B("Ariel","Sylvia Plath","USA",1965,"Verse & Stage","r","Lady Lazarus rises; poetry scorches.","In daylight, with care."),
B("Milk and Honey","Rupi Kaur","India/Canada",2014,"Verse & Stage","c","Instagram's poet laureate; the gateway shelf.","Then climb toward Ghalib."),
B("The Essential Rumi","Rumi","Persia",1995,"Verse & Stage","c","The bestselling poet in America is 800 years old.","One poem before sleep."),
B("Where the Sidewalk Ends","Shel Silverstein","USA",1974,"Verse & Stage","c","Childhood's absurd, tender national anthem.","Aloud to any child available."),
// ---- FINAL SHELF ----
B("The Master of Go","Yasunari Kawabata","Japan",1951,"World","r","A single Go match as the death of old Japan.","With the board diagrams studied."),
B("Silence","Shūsaku Endō","Japan",1966,"World","r","Faith tested in hidden-Christian Japan.","Then Scorsese's adaptation."),
B("A Personal Matter","Kenzaburō Ōe","Japan",1964,"World","r","A father flees, then faces, his newborn's fate.","Unflinchingly; it earns its Nobel."),
B("The Pillow Book","Sei Shōnagon","Japan",1002,"World","r","A courtier's lists: elegant, catty, immortal.","Dip anywhere; it's a mosaic."),
B("Musashi","Eiji Yoshikawa","Japan",1935,"World","u","The sword-saint's epic; Japan's Gone with the Wind.","A samurai summer."),
B("Shōgun","James Clavell","England",1975,"World","u","An English pilot washes into 1600 Japan.","A holiday brick; it flies."),
B("Memoirs of a Geisha","Arthur Golden","USA",1997,"World","c","Gion's water trade through one woman's eyes.","Then read Iwasaki's real memoir."),
B("Balzac and the Little Chinese Seamstress","Dai Sijie","China",2000,"World","u","Forbidden books re-educate the re-educated.","One evening; it's a fable."),
B("The Sympathizer","Viet Thanh Nguyen","Vietnam/USA",2015,"Modern & Contemporary","r","A double agent's confession; Vietnam answers back.","The squid scene is a rite of passage."),
B("The Quiet American","Graham Greene","England",1955,"Classics","u","Innocence as a form of violence, in Saigon.","At the Continental, ideally."),
B("The Power and the Glory","Graham Greene","England",1940,"Classics","r","A whisky priest runs from martyrdom, badly.","With mezcal understanding."),
B("A House for Mr Biswas","V.S. Naipaul","Trinidad",1961,"World","r","One man, one house, one lifetime of almost.","Patiently; the house gets built."),
B("Wide Sargasso Sea","Jean Rhys","Dominica",1966,"World","r","Jane Eyre's madwoman gets her side told.","Right after Jane Eyre."),
B("The Famished Road","Ben Okri","Nigeria",1991,"World","r","A spirit-child keeps choosing to stay.","Dreamlike stretches; don't rush."),
B("Nervous Conditions","Tsitsi Dangarembga","Zimbabwe",1988,"World","r","A girl's education against everything.","With its two sequels queued."),
B("Cry, the Beloved Country","Alan Paton","South Africa",1948,"Classics","u","A father's search through apartheid's dawn.","With the hymn-like prose aloud."),
B("The Sellout","Paul Beatty","USA",2015,"Modern & Contemporary","r","Satire so sharp the Booker cut itself.","Prologue aloud; commit from there."),
B("Lincoln in the Bardo","George Saunders","USA",2017,"Modern & Contemporary","r","A president grieves among the chatty dead.","The audiobook's 166 voices, ideally."),
B("Tenth of December","George Saunders","USA",2013,"Modern & Contemporary","u","Kindness engineered in ten strange stories.","One story per lunch."),
B("Olive Kitteridge","Elizabeth Strout","USA",2008,"Modern & Contemporary","u","A difficult woman, loved in thirteen stories.","Coastal weather helps."),
B("Gilead","Marilynne Robinson","USA",2004,"Modern & Contemporary","r","A dying preacher's letter; grace in prose form.","Slowly, like light through dust."),
B("Stoner","John Williams","USA",1965,"Modern & Contemporary","r","An ordinary life, perfectly told; the cult grows.","Quietly; then press it on someone."),
B("A Confederacy of Dunces","John Kennedy Toole","USA",1980,"Modern & Contemporary","u","Ignatius J. Reilly versus New Orleans; posthumous Pulitzer.","With a hot dog, laughing."),
B("The Bell Jar","Sylvia Plath","USA",1963,"Modern & Contemporary","u","The fig tree passage alone explains a generation.","With care and company after."),
B("On the Road","Jack Kerouac","USA",1957,"Modern & Contemporary","u","The scroll that launched a million road trips.","Fast, forgiving, then Vesuvio."),
B("Fear and Loathing in Las Vegas","Hunter S. Thompson","USA",1971,"Modern & Contemporary","u","Gonzo's high-water mark; the wave speech endures.","Not as an instruction manual."),
B("One Flew Over the Cuckoo's Nest","Ken Kesey","USA",1962,"Modern & Contemporary","u","McMurphy versus the Combine.","Then the film; both are canon."),
B("The Shining","Stephen King","USA",1977,"Modern & Contemporary","c","The Overlook checks in; winter does the rest.","Off-season, in any old hotel."),
B("It","Stephen King","USA",1986,"Modern & Contemporary","u","Childhood's monster given 1,100 pages.","A summer; float through."),
B("11/22/63","Stephen King","USA",2011,"SF & Fantasy","u","A diner door opens onto 1958; Dallas waits.","A long weekend; it compels."),
B("The Stand","Stephen King","USA",1978,"SF & Fantasy","r","Plague, then prophecy; King's American epic.","The uncut edition, over a month."),
B("Jurassic Park","Michael Crichton","USA",1990,"SF & Fantasy","c","Chaos theory with teeth.","Faster than the movie; read it."),
B("The Time Machine","H.G. Wells","England",1895,"SF & Fantasy","u","802,701 AD reached in 90 pages.","One Victorian evening."),
B("The War of the Worlds","H.G. Wells","England",1898,"SF & Fantasy","u","Martians vs. Surrey; the panic template.","Then the 1938 broadcast."),
B("Twenty Thousand Leagues Under the Seas","Jules Verne","France",1870,"SF & Fantasy","u","Nemo's Nautilus; wonder invented.","With squid respect."),
B("Flowers for Algernon","Daniel Keyes","USA",1966,"SF & Fantasy","u","IQ rises and falls; your heart follows.","One sitting; the spelling is the plot."),
B("Station Eleven","Emily St. John Mandel","Canada",2014,"SF & Fantasy","u","Survival is insufficient; Shakespeare after the fall.","Post-2020, it reads differently."),
B("Exhalation","Ted Chiang","USA",2019,"SF & Fantasy","r","Nine stories; each one a philosophy degree.","One story, one long walk."),
B("Stories of Your Life and Others","Ted Chiang","USA",2002,"SF & Fantasy","r","The story that became Arrival, plus peers.","Before the film if possible."),
B("Mistborn","Brandon Sanderson","USA",2006,"SF & Fantasy","c","Heist crew versus god-emperor; magic with rules.","The trilogy; the ending pays."),
B("The Way of Kings","Brandon Sanderson","USA",2010,"SF & Fantasy","r","1,000 pages of storms and oaths; book one of ten.","Commit or don't; no half measures."),
B("The Blade Itself","Joe Abercrombie","England",2006,"SF & Fantasy","u","Grimdark's charming, limping entrance.","Say one thing for Logen: read it."),
B("The Lies of Locke Lamora","Scott Lynch","USA",2006,"SF & Fantasy","u","Ocean's Eleven in fantasy Venice.","With the Gentleman Bastards toasted."),
B("Circe","Madeline Miller","USA",2018,"SF & Fantasy","c","The witch of Aiaia writes her own myth.","Sea air optional but right."),
B("The Song of Achilles","Madeline Miller","USA",2011,"SF & Fantasy","c","Patroclus and Achilles; the Iliad's heart exposed.","Tissues by the final chapters."),
B("The Overstory","Richard Powers","USA",2018,"Modern & Contemporary","r","Trees as protagonists; humans as weather.","Then hug one, unironically."),
B("All the Light We Cannot See","Anthony Doerr","USA",2014,"Modern & Contemporary","c","A blind girl, a radio, Saint-Malo burning.","Short chapters; long feelings."),
B("The Book Thief","Markus Zusak","Australia",2005,"Modern & Contemporary","c","Death narrates; a girl steals books in the Reich.","Keep the last pages for privacy."),
B("Where the Crawdads Sing","Delia Owens","USA",2018,"Modern & Contemporary","c","The marsh girl; the phenomenon.","One humid weekend."),
B("Eleanor Oliphant Is Completely Fine","Gail Honeyman","Scotland",2017,"Modern & Contemporary","c","She is not, and that's the point.","With growing tenderness."),
B("A Man Called Ove","Fredrik Backman","Sweden",2012,"Modern & Contemporary","c","A grump adopted by a neighborhood.","Then forgive one neighbor."),
B("Beartown","Fredrik Backman","Sweden",2016,"Modern & Contemporary","u","A hockey town's loyalty, stress-tested.","With your hometown in mind."),
B("My Year of Rest and Relaxation","Ottessa Moshfegh","USA",2018,"Modern & Contemporary","u","Sleeping through 2000; a nap as protest.","In bed, obviously."),
B("Conversations with Friends","Sally Rooney","Ireland",2017,"Modern & Contemporary","c","Cool prose, warm wounds.","Alongside strong opinions about it."),
B("Klara and the Sun","Kazuo Ishiguro","England",2021,"SF & Fantasy","u","An Artificial Friend studies love and the Sun.","Gently; Klara deserves it."),
B("Tomorrow, and Tomorrow, and Tomorrow","Gabrielle Zevin","USA",2022,"Modern & Contemporary","c","Thirty years of friendship, rendered in games.","With your oldest collaborator in mind."),
B("Lessons in Chemistry","Bonnie Garmus","USA",2022,"Modern & Contemporary","c","A chemist teaches a nation to cook and rebel.","With dinner underway."),
B("Demon Copperhead","Barbara Kingsolver","USA",2022,"Modern & Contemporary","u","David Copperfield reborn in opioid Appalachia.","After or instead of Dickens."),
B("Prophet Song","Paul Lynch","Ireland",2023,"Modern & Contemporary","r","Ireland slides into dictatorship; a mother holds on.","Breathless; the sentences don't stop."),
B("Orbital","Samantha Harvey","England",2023,"Modern & Contemporary","u","Sixteen sunrises, one space station, all of Earth.","In one orbit of an evening."),
B("The Covenant of Water","Abraham Verghese","India/USA",2023,"India","u","Kerala, three generations, water keeps its ledger.","A monsoon month."),
B("Cutting for Stone","Abraham Verghese","India/USA",2009,"World","u","Twin surgeons, Addis to New York.","With Marion's voice trusted."),
B("Gun Island","Amitav Ghosh","India",2019,"India","u","Myth and migration in a warming world.","Then The Great Derangement."),
B("The Shadow Lines","Amitav Ghosh","India",1988,"India","r","Borders drawn on water; memory refuses them.","In one absorbed weekend."),
B("Sea of Poppies","Amitav Ghosh","India",2008,"India","r","The Ibis sails; opium, indenture, empire.","With the glossary of laskari tongue."),
B("The City of Djinns","William Dalrymple","Scotland/India",1993,"Lives & Journeys","u","A year in Delhi, seven cities deep.","In Delhi winter, ideally."),
B("Nine Lives","William Dalrymple","Scotland/India",2009,"Lives & Journeys","r","Nine sacred lives modern India hasn't erased.","One life per evening."),
B("Behind the Beautiful Forevers","Katherine Boo","USA",2012,"Lives & Journeys","r","Annawadi, by the airport, invisible no more.","Then look out the plane window differently."),
B("Freedom at Midnight","Larry Collins & Dominique Lapierre","France/USA",1975,"Ideas & Science","u","1947 hour by hour; history as thriller.","Around every August 15th."),
B("The Last Mughal","William Dalrymple","Scotland/India",2006,"Ideas & Science","r","1857 and the end of an era, from Delhi's streets.","With Ghalib's letters alongside."),
B("Empire of Pain","Patrick Radden Keefe","USA",2021,"Ideas & Science","u","The Sacklers, indicted in 500 pages.","With rising, useful anger."),
B("Say Nothing","Patrick Radden Keefe","USA",2018,"Ideas & Science","r","The Troubles via one disappearance.","Then the McConville coverage."),
B("Bad Blood","John Carreyrou","USA",2018,"Ideas & Science","c","Theranos, bled dry by one reporter.","Mandatory VC reading; one weekend."),
B("The Big Short","Michael Lewis","USA",2010,"Ideas & Science","c","The men who shorted the apocalypse.","Then Margin Call, then Moneyball."),
B("Liar's Poker","Michael Lewis","USA",1989,"Ideas & Science","u","Wall Street's locker room, 1980s edition.","Before your first bonus."),
B("Barbarians at the Gate","Bryan Burrough & John Helyar","USA",1989,"Ideas & Science","r","RJR Nabisco; the LBO circus at full tilt.","With popcorn; it's a heist."),
B("Ikigai","Héctor García & Francesc Miralles","Spain",2016,"Ideas & Science","c","Okinawa's reason-to-wake-up, bottled.","With your own ikigai sketched."),
B("The Almanack of Naval Ravikant","Eric Jorgenson","USA",2020,"Ideas & Science","c","Wealth and happiness, tweeted then bound.","Dip anywhere; it's modular."),
B("Four Thousand Weeks","Oliver Burkeman","England",2021,"Ideas & Science","u","Your whole life is 4,000 weeks; plan accordingly.","Then delete a to-do list."),
B("Deep Work","Cal Newport","USA",2016,"Ideas & Science","c","Focus as the superpower of the century.","Phone in another room."),
B("The Psychology of Money","Morgan Housel","USA",2020,"Ideas & Science","c","Twenty timeless lessons; zero formulas.","One chapter per payday."),
B("The Tao Te Ching","Laozi","China",-400,"Ideas & Science","u","81 verses; the water always wins.","One verse per morning, forever."),
B("The Analects","Confucius","China",-450,"Ideas & Science","r","The teacher's fragments that built East Asia.","With commentary at elbow."),
B("The Upanishads","Various","India",-700,"India","r","Tat tvam asi: you are that.","With a patient translation."),
B("Autobiography of a Yogi","Paramahansa Yogananda","India",1946,"Lives & Journeys","u","The book on Steve Jobs' iPad, on loop.","With skepticism and wonder both."),
B("The Book of Five Rings","Miyamoto Musashi","Japan",1645,"Ideas & Science","u","Strategy from a duelist who never lost.","Before any competition."),
B("Zen and the Art of Motorcycle Maintenance","Robert M. Pirsig","USA",1974,"Ideas & Science","r","Quality, chased across America on two wheels.","On a long ride's rest days."),
B("Charlotte's Web","E.B. White","USA",1952,"Classics","c","Some pig; the kindest book about death.","Aloud to anyone."),
B("The Wind in the Willows","Kenneth Grahame","England",1908,"Classics","c","Messing about in boats; England's gentlest dream.","Riverbank picnic reading."),
B("Alice's Adventures in Wonderland","Lewis Carroll","England",1865,"Classics","c","Logic on holiday; we're all mad here.","Then the annotated edition."),
B("The Chronicles of Narnia","C.S. Lewis","England",1950,"SF & Fantasy","c","A wardrobe opens; a century of readers follows.","Publication order; fight me."),
B("Matilda","Roald Dahl","England",1988,"Classics","c","A reader's revenge fantasy, perfected.","With a library card renewed."),
B("The Godfather","Mario Puzo","USA",1969,"Mystery & Noir","c","The offer, the horse, the family business.","Before the films, once in life."),
B("Chronicle of a Death Foretold","Gabriel García Márquez","Colombia",1981,"World","u","Everyone knew; nobody stopped it.","One sitting; the title is the spoiler."),
B("The Old Patagonian Express","Paul Theroux","USA",1979,"Lives & Journeys","r","Boston to Patagonia entirely by rail.","On any long train south."),
B("The Great Railway Bazaar","Paul Theroux","USA",1975,"Lives & Journeys","r","Four months of Asia by train; the genre reborn.","Before your own rail epic."),
B("Vagabonding","Rolf Potts","USA",2002,"Lives & Journeys","c","Long-term travel as a learnable art.","Before quitting anything."),
B("Eat, Pray, Love","Elizabeth Gilbert","USA",2006,"Lives & Journeys","c","Italy, India, Indonesia; a divorce's world tour.","Judgment-free; it earns its fans."),
B("The Beach","Alex Garland","England",1996,"Modern & Contemporary","c","Paradise found; paradise policed.","In a hostel dorm, ideally."),
B("A Moveable Feast","Ernest Hemingway","USA",1964,"Lives & Journeys","u","Paris in the twenties; hunger as seasoning.","In a café, notebook out."),
B("The Sun Also Rises","Ernest Hemingway","USA",1926,"Classics","u","Pamplona, prewar wounds, and one tight sentence.","Around a festival, any festival."),
B("Giovanni's Room","James Baldwin","USA",1956,"Classics","r","Paris, desire, and the closet's architecture.","In one honest evening."),
B("The Fire Next Time","James Baldwin","USA",1963,"Ideas & Science","u","Two letters that still read like tomorrow.","Aloud, some paragraphs."),
B("Go Tell It on the Mountain","James Baldwin","USA",1953,"Classics","r","One Harlem Saturday; three generations of fire.","With gospel playing."),
B("Bury My Heart at Wounded Knee","Dee Brown","USA",1970,"Ideas & Science","r","The West's history, told from the other side.","Chapter by chapter; let it count."),
B("1491","Charles C. Mann","USA",2005,"Ideas & Science","r","The Americas before Columbus: fuller than taught.","With old maps redrawn in your head."),
B("Salt","Mark Kurlansky","USA",2002,"Ideas & Science","u","Civilization, seasoned; one mineral's world tour.","With dinner history-checked."),
B("The Omnivore's Dilemma","Michael Pollan","USA",2006,"Ideas & Science","u","Four meals traced to their roots.","Before your next grocery run."),
B("Salt Fat Acid Heat","Samin Nosrat","USA",2017,"Ideas & Science","c","Cooking's four forces, finally named.","In the kitchen, flour on it.")

];

registerCatalog("books", BOOKS.map((b, i) => ({ id: "bk" + String(i + 1).padStart(3, "0"), ...b, leg: b.tier === "l" })));
