/* DubaiDex — the hidden city. No postcards, no attractions:
   the version of Dubai that residents guard and tourists miss. */
registerCatalog("dubai", [
// THE KEYS TO THE CITY (legendaries)
{id:"du001",name:"Abra Across the Creek at Sunset",cat:"Old Dubai",style:"1 Dirham Ritual",country:"Dubai Creek",stat:"1 AED",tags:["wooden boat","golden hour","oldest commute"],fact:"The best 1-dirham purchase on Earth — a working commute, unchanged for a century.",serve:"Deira to Bur Dubai side, 15 minutes before sunset.",leg:true},
{id:"du002",name:"Fog Rolling Over the Marina",cat:"Only in Dubai",style:"Cloud City",country:"Dubai Marina",stat:"Sept–Nov dawns",tags:["towers as islands","rare","alarm worthy"],fact:"A few autumn dawns a year, the city drowns in cloud and only its ambitions poke out.",serve:"Watch the fog forecast; a high floor, before 6:30am.",leg:true},
{id:"du003",name:"Empty Quarter Overnight",cat:"Desert",style:"Rub' al Khali",country:"Liwa edge",stat:"300m dunes",tags:["largest sand desert","true silence","star ceiling"],fact:"The Empty Quarter could swallow France. At night it swallows sound itself.",serve:"Winter, guided convoy, sleep outside the tent.",leg:true},
{id:"du004",name:"Ramadan Iftar With Strangers",cat:"Only in Dubai",style:"Open Table",country:"Any mosque courtyard",stat:"Sunset sharp",tags:["dates first","community","invited always"],fact:"During Ramadan, every mosque courtyard becomes the world's most welcoming table.",serve:"Arrive 20 min early, accept everything, thank in Arabic.",leg:true},
{id:"du005",name:"A Majlis Invitation",cat:"Only in Dubai",style:"The Real Key",country:"An Emirati home",stat:"Gahwa & dates",tags:["family majlis","gahwa ritual","earned not booked"],fact:"No ticket exists for this. A seat in a family majlis means the city has decided to know you.",serve:"Right hand for gahwa; shake the cup gently when done.",leg:true},
// OLD DUBAI
{id:"du006",name:"Al Fahidi at 7am",cat:"Old Dubai",style:"Wind-Tower Quarter",country:"Bur Dubai",stat:"1890s lanes",tags:["barjeel","coral walls","before the heat"],fact:"The wind towers are pre-electric air conditioning that still works — best felt in empty morning lanes.",serve:"Sunrise walk, end at Arabian Tea House."},
{id:"du007",name:"Arabian Tea House Breakfast",cat:"Old Dubai",style:"Emirati Morning",country:"Al Fahidi",stat:"Since 1997",tags:["balaleet","chebab","courtyard"],fact:"Sweet vermicelli under an omelette is the correct Emirati breakfast. Trust it.",serve:"Balaleet + karak, courtyard table, no rush."},
{id:"du008",name:"Dhow Wharfage Walk",cat:"Old Dubai",style:"Working Harbor",country:"Deira Creek",stat:"Iran–Somalia routes",tags:["wooden ships","cargo tetris","trade alive"],fact:"These wooden dhows still run real trade routes — fridges to Somalia, tyres to Iran, tea everywhere.",serve:"Late afternoon; watch the loading, ask before photos."},
{id:"du009",name:"Textile Souk to Tailor in 48 Hours",cat:"Old Dubai",style:"Fabric to Fit",country:"Bur Dubai",stat:"48h turnaround",tags:["silk walls","measurements","old craft"],fact:"Pick a fabric, get measured over chai, wear it in two days — the old city's quiet superpower.",serve:"Morning fabric hunt, tailor by lunch."},
{id:"du010",name:"Heritage Pearl Dive",cat:"Old Dubai",style:"Before Oil",country:"With the Suwaidi family",stat:"1 oyster",tags:["nose clip","diving songs","found a pearl?"],fact:"Two generations ago this city's entire economy fit inside an oyster.",serve:"Open your own; keep whatever you find."},
{id:"du011",name:"Bur Dubai Temple Lane at Aarti Hour",cat:"Old Dubai",style:"Hidden Devotion",country:"Meena Bazaar",stat:"Dusk bells",tags:["1958 temple","jasmine sellers","layered city"],fact:"A Hindu temple lane has run beside the mosque and the creek since 1958 — the city's oldest coexistence.",serve:"Dusk, flowers from the lane stalls, walk quietly."},
{id:"du012",name:"Naif Midnight Market Crawl",cat:"Old Dubai",style:"Deira After Dark",country:"Naif, Deira",stat:"Post 11pm",tags:["perfume alleys","chai stalls","the real souk"],fact:"When the tour groups sleep, Naif wakes — the unpolished souk where Deira actually shops.",serve:"Go hungry, follow the crowds, haggle gently."},
{id:"du013",name:"Jumeirah Mosque, Doors Open",cat:"Old Dubai",style:"Ask Anything",country:"Jumeirah",stat:"Open to all",tags:["open doors open minds","any faith","questions welcome"],fact:"The mosque runs 'open doors, open minds' sessions where no question is off the table.",serve:"Morning tour; the questions are the point."},
// DESERT
{id:"du014",name:"Al Qudra Sunrise Cycle",cat:"Desert",style:"86km Loop",country:"Al Qudra",stat:"5:45 am start",tags:["oryx crossings","peloton culture","desert road"],fact:"A cycling superhighway through open desert — oryx have right of way.",serve:"Rent at the Trek hub; done before 9am heat."},
{id:"du015",name:"Wild Camp at the Qudra Lakes",cat:"Desert",style:"Self-Drive Night",country:"Al Marmoom",stat:"0 walls",tags:["byo firewood","stars","free"],fact:"No resort, no ticket — drive out, build a fire, and the desert is yours till fajr.",serve:"Winter weeknight; pack out every trace."},
{id:"du016",name:"Love Lake at Flamingo Dawn",cat:"Desert",style:"Improbable Wetland",country:"Al Qudra",stat:"6 am",tags:["heart-shaped lakes","wild flamingos","mist"],fact:"Man-made lakes the desert adopted — flamingos now winter in a heart drawn in sand.",serve:"First light, thermos of karak, binoculars."},
{id:"du017",name:"Mleiha Fossil Rock Hike",cat:"Desert",style:"Ancient Seabed",country:"Mleiha",stat:"70M years",tags:["marine fossils","in a desert","sunset ridge"],fact:"The desert floor here was ocean — the fossils in the rock prove it.",serve:"Winter afternoon; guided fossil walk, ridge for sunset."},
{id:"du018",name:"Al Madam Ghost Village",cat:"Desert",style:"Buried Houses",country:"Al Madam edge",stat:"Half-swallowed",tags:["abandoned 90s village","sand-filled rooms","eerie gold hour"],fact:"A village the dunes are eating room by room — sand pours through the windows like slow water.",serve:"Golden hour; walk the buried majlis, take nothing."},
// EAT LIKE A LOCAL
{id:"du019",name:"Ravi After Midnight",cat:"Eat Like a Local",style:"Institution",country:"Satwa",stat:"Since 1978",tags:["butter chicken","plastic chairs","every class of car outside"],fact:"Lamborghinis and labourers share the same plastic chairs here. Nobody finds it strange.",serve:"1am, butter chicken + kandahari naan."},
{id:"du020",name:"Bu Qtair Fish Shack",cat:"Eat Like a Local",style:"Catch of the Day",country:"Umm Suqeim",stat:"By the kilo",tags:["masala fried","paper plates","queue of those who know"],fact:"A fishing-family shack that outlasted every trend built around it.",serve:"Point at the fish, take the curry sauce."},
{id:"du021",name:"3am Karak Run",cat:"Eat Like a Local",style:"Cafeteria Culture",country:"Any cafeteria window",stat:"1.5 AED",tags:["car window service","condensed milk","the ritual"],fact:"Honking gently at a cafeteria window is a legitimate ordering system.",serve:"Karak + chips oman sandwich, car bonnet seating."},
{id:"du022",name:"Special Ostadi Kebab",cat:"Eat Like a Local",style:"Iranian Institution",country:"Meena Bazaar",stat:"Since 1978",tags:["yoghurt kebab","photo walls","three generations"],fact:"Three generations of the same family at the same grill, walls papered with regulars.",serve:"Chelo kebab under the photo wall."},
{id:"du023",name:"Fishermen's Harbour Chai at 6am",cat:"Eat Like a Local",style:"Working Breakfast",country:"Jumeirah Fishing Harbour",stat:"6 am",tags:["boats in","gulls","paratha"],fact:"Breakfast tastes different when the fish arriving beside you is tonight's dinner.",serve:"Follow the fishermen, order what they order."},
{id:"du024",name:"Kunafa Crawl, Deira vs Sharjah Road",cat:"Eat Like a Local",style:"Cheese Pull Science",country:"Firas & rivals",stat:"90 seconds",tags:["nabulsi","orange strands","diaspora politics"],fact:"Dubai's kunafa rivalry is Levantine politics in dessert form. Pick a side carefully.",serve:"Eat within 90 seconds of serving. Non-negotiable."},
{id:"du025",name:"Karama Ghar Ka Khana Thali",cat:"Eat Like a Local",style:"Little India",country:"Karama",stat:"20 AED",tags:["unlimited refills","steel plates","office crowd"],fact:"Karama's lunch canteens feed more people daily than most festivals.",serve:"Lunch rush; follow the office crowd, refuse nothing."},
{id:"du026",name:"Machboos at a Local Beit",cat:"Eat Like a Local",style:"The National Dish",country:"Al Khayma & similar",stat:"Loomi power",tags:["dried lime","rice mastery","floor seating"],fact:"Loomi — sun-dried lime — is the flavor key to the entire Emirati kitchen.",serve:"Right hand if you're brave, mounds of it."},
{id:"du027",name:"Al Aweer Fruit Market at 4am",cat:"Eat Like a Local",style:"Wholesale Theatre",country:"Al Aweer",stat:"4 am peak",tags:["mango season","by the box","trader shouts"],fact:"Mango season here is a full subcontinental diplomatic event.",serve:"June for mangoes; buy a box, share it at work."},
{id:"du028",name:"Mandi Lunch in Frij Murar",cat:"Eat Like a Local",style:"Yemeni Backstreet",country:"Deira",stat:"Floor seating",tags:["smoked lamb","rice mountains","hands only"],fact:"Deira's Yemeni canteens serve mandi the way Sana'a intended — on the floor, by the hand, in silence.",serve:"Share a lamb quarter; eat with your right, mop with bread."},
{id:"du029",name:"Waterfront Fish Auction at 5am",cat:"Eat Like a Local",style:"Dawn Commerce",country:"Waterfront Market, Deira",stat:"5 am",tags:["hamour & sheri","auction shouts","ice mountains"],fact:"The city's fish changes hands here at volume and speed tourists never witness.",serve:"Buy a sheri, have the grill stall cook it for breakfast."},
// ONLY IN DUBAI
{id:"du030",name:"Hatta Kayak Before the Crowds",cat:"Only in Dubai",style:"Mountain Exclave",country:"Hatta Dam",stat:"90 min drive",tags:["turquoise water","hajar mountains","dubai? yes"],fact:"Technically Dubai, spiritually another country.",serve:"First slot of a winter weekday; honey farm after."},
{id:"du031",name:"Ras Al Khor Flamingo Hide",cat:"Only in Dubai",style:"Wetland vs Skyline",country:"Ras Al Khor",stat:"Free entry",tags:["500+ birds","free hides","surreal"],fact:"Wild flamingos feed with the skyline behind them — free, and somehow still empty.",serve:"Winter mornings, Mangrove hide."},
{id:"du032",name:"Quranic Park Cave at Dusk",cat:"Only in Dubai",style:"Garden of Stories",country:"Al Khawaneej",stat:"Free entry",tags:["plants of scripture","glass cave","local families"],fact:"Every plant mentioned in the Quran grows in one garden almost no visitor finds.",serve:"Winter evening walk; the cave last."},
{id:"du033",name:"Metro Front Window at Sunset",cat:"Only in Dubai",style:"Driverless View",country:"Red Line",stat:"90 km/h",tags:["no driver","skyline rail","commuter secret"],fact:"Driverless means the front window is anyone's — the city's cheapest scenic flight.",serve:"Front cabin, Expo-bound, golden hour."},
{id:"du034",name:"Last Exit Night Run",cat:"Only in Dubai",style:"Route Ritual",country:"E11 edges",stat:"1 road trip",tags:["mad max theme","truck stops","desert highway"],fact:"A Mad Max-themed food truck stop in open desert. Because someone in Dubai said why not.",serve:"Night drive, one burger, one karak."},
{id:"du035",name:"Alserkal Avenue + Cinema Akil",cat:"Only in Dubai",style:"Warehouse Culture",country:"Al Quoz",stat:"Double bill",tags:["galleries in warehouses","indie cinema","chai between"],fact:"The city's art scene lives in industrial warehouses — anchored by the Gulf's only arthouse cinema.",serve:"Gallery loop, then whatever Akil is screening."},
{id:"du036",name:"Friday Cricket With the Taxi Drivers",cat:"Only in Dubai",style:"Parking Lot League",country:"Al Quoz / Sonapur lots",stat:"Tape ball",tags:["100 matches at once","tape ball","the real UAE"],fact:"Every Friday, empty lots become a hundred simultaneous cricket grounds — the city's truest sport.",serve:"Ask to field first. You'll be batting by chai time."}
]);
